Script started on 2024-11-20 23:09:49+00:00 [TERM="screen" TTY="/dev/pts/1" COLUMNS="255" LINES="27"]
[?2004h(base) ubuntu@ip-10-0-0-196:/fsx/analysis_results/ubuntu/hg38/hg005hg007/daylily$ exitsudo su ubuntuexit[K[KR[3mscript workflow/scripts/calc_norm_cov_sd.R results/day/hg38/RIH0_ANA0-HG004-19_DBC0_0/align/bwa2a/alignqc/norm_cov_eveness/RIH0_ANA0-HG004-19_DBC0_0.bwa2a.md.chr$i.regions.[23m[3mb[23m[3med.gz  RIH0_ANA0-HG004-19_DBC0_0_$alnr_chr$i chr$i [23mM[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Cscript workflow/scripts/calc_norm_cov_sd.R results/day/hg38/RIH0_ANA0-HG004-19_DBC0_0/align/bwa2a/alignqc/norm_cov_eveness/RIH0_ANA0-HG004-19_DBC0_0.bwa2a.md.chr$i.regions.bed.gz  RIH0_ANA0-HG004-19_DBC0_0_$alnr_chr$i chr$i 
[?2004l[?2004h(base) ubuntu@ip-10-0-0-196:/fsx/analysis_results/ubuntu/hg38/hg005hg007/daylily$ Rscript
[?2004lUsage: /path/to/Rscript [--options] [-e expr [-e expr2 ...] | file] [args]

--options accepted are
  --help              Print usage and exit
  --version           Print version and exit
  --verbose           Print information on progress
  --default-packages=list
                      Where 'list' is a comma-separated set
                        of package names, or 'NULL'
or options to R, in addition to --no-echo --no-restore, such as
  --save              Do save workspace at the end of the session
  --no-environ        Don't read the site and user environment files
  --no-site-file      Don't read the site-wide Rprofile
  --no-init-file      Don't read the user R profile
  --restore           Do restore previously saved objects at startup
  --vanilla           Combine --no-save, --no-restore, --no-site-file
                        --no-init-file and --no-environ

'file' may contain spaces but not shell metacharacters
Expressions (one or more '-e <expr>') may be used *instead* of 'file'
See also  ?Rscript  from within R
[?2004h(base) ubuntu@ip-10-0-0-196:/fsx/analysis_results/ubuntu/hg38/hg005hg007/daylily$ Rscript workflow/scripts/calc_norm_cov_sd.R results/day/hg38/RIH0_ANA0-HG004-19_DBC0_0/align/bwa2a/alignqc/norm_cov_eveness/RIH0_ANA0-HG004-19_DBC0_0.bwa2a.md.chr$i.regions.bed.gz  RIH0_ANA0-HG004-19_DBC0_0_$alnr_chr$i chr$i 
[?2004l[?2004h(base) ubuntu@ip-10-0-0-196:/fsx/analysis_results/ubuntu/hg38/hg005hg007/daylily$ Rscript workflow/scripts/calc_norm_cov_sd.R results/day/hg38/RIH0_ANA0-HG004-19_DBC0_0/align/bwa2a/alignqc/norm_cov_eveness/RIH0_ANA0-HG004-19_DBC0_0.bwa2a.md.chr$i.regions.bed.gz  RIH0_ANA0-HG004-19_DBC0_0_$alnr_chr$i chr$i [K[K[K[K[K[K[K[K[K[K[K[K[K[K
[?2004l[?2004h(base) ubuntu@ip-10-0-0-196:/fsx/analysis_results/ubuntu/hg38/hg005hg007/daylily$ Rscript workflow/scripts/calc_norm_cov_sd.R results/day/hg38/RIH0_ANA0-HG004-19_DBC0_0/align/bwa2a/alignqc/norm_cov_eveness/RIH0_ANA0-HG004-19_DBC0_0.bwa2a.md.chr$i.regions.bed.gz  RIH0_ANA0-HG004-19_DBC0_0_$aln[K[K[K[K[K[K[K[K[K[K[K[K
[?2004l[?2004h(base) ubuntu@ip-10-0-0-196:/fsx/analysis_results/ubuntu/hg38/hg005hg007/daylily$ [K(base) ubuntu@ip-10-0-0-196:/fsx/analysis_results/ubuntu/hg38/hg005hg007/daylily$ more [3mresults/day/hg38/RIH0_ANA0-HG004-19_DBC0_0/align/bwa2a/alignqc/norm_cov_eveness/RIH0_ANA0-HG004-19_DBC0_0.bwa2a.md.chr$i.regions.bed.gz [23m[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Cresults/day/hg38/RIH0_ANA0-HG004-19_DBC0_0/align/bwa2a/alignqc/norm_cov_eveness/RIH0_ANA0-HG004-19_DBC0_0.bwa2a.md.chr$i.regions.bed.gz 
[?2004lmore: cannot open results/day/hg38/RIH0_ANA0-HG004-19_DBC0_0/align/bwa2a/alignqc/norm_cov_eveness/RIH0_ANA0-HG004-19_DBC0_0.bwa2a.md.chr.regions.bed.gz: No such file or directory
[?2004h(base) ubuntu@ip-10-0-0-196:/fsx/analysis_results/ubuntu/hg38/hg005hg007/daylily$ find results/ | grep giabhcr
[?2004lresults/day/MQ/SEQQC_multiqc_data/multiqc_[01;31m[Kgiabhcr[m[K_concordance.txt
results/day/MQ/DAY_final_multiqc_data/multiqc_[01;31m[Kgiabhcr[m[K_concordance.txt
results/day/MQ/SEQQC_multiqc_plots/svg/[01;31m[Kgiabhcr[m[K_concordance.svg
results/day/MQ/SEQQC_multiqc_plots/png/[01;31m[Kgiabhcr[m[K_concordance.png
results/day/MQ/SEQQC_multiqc_plots/pdf/[01;31m[Kgiabhcr[m[K_concordance.pdf
results/day/MQ/DAY_final_multiqc_plots/svg/[01;31m[Kgiabhcr[m[K_concordance.svg
results/day/MQ/DAY_final_multiqc_plots/png/[01;31m[Kgiabhcr[m[K_concordance.png
results/day/MQ/DAY_final_multiqc_plots/pdf/[01;31m[Kgiabhcr[m[K_concordance.pdf
results/day/hg38/other_reports/[01;31m[Kgiabhcr[m[K_concordance_mqc.tsv
results/day/hg38/reports/SEQQC_multiqc_plots/svg/[01;31m[Kgiabhcr[m[K_concordance.svg
results/day/hg38/reports/SEQQC_multiqc_plots/png/[01;31m[Kgiabhcr[m[K_concordance.png
results/day/hg38/reports/SEQQC_multiqc_plots/pdf/[01;31m[Kgiabhcr[m[K_concordance.pdf
results/day/hg38/reports/SEQQC_multiqc_data/multiqc_[01;31m[Kgiabhcr[m[K_concordance.txt
results/day/hg38/reports/DAY_final_multiqc_data/multiqc_[01;31m[Kgiabhcr[m[K_concordance.txt
[?2004h(base) ubuntu@ip-10-0-0-196:/fsx/analysis_results/ubuntu/hg38/hg005hg007/daylily$ find results/ | grep giabhcr[K[K [K[K | grep _mqc
[?2004lresults/day/hg38/other_reports/giab_concordance[01;31m[K_mqc[m[K.tsv
results/day/hg38/other_reports/giabhcr_concordance[01;31m[K_mqc[m[K.tsv
[?2004h(base) ubuntu@ip-10-0-0-196:/fsx/analysis_results/ubuntu/hg38/hg005hg007/daylily$ find results/ | grep giab | grep _mqc | parallel 'ls -lth {}'
[?2004l-rw-rw-r-- 1 ubuntu ubuntu 50K Nov 20 22:37 results/day/hg38/other_reports/giab_concordance_mqc.tsv
-rw-rw-r-- 1 ubuntu ubuntu 3.7K Nov 19 07:52 results/day/hg38/other_reports/giabhcr_concordance_mqc.tsv
[?2004h(base) ubuntu@ip-10-0-0-196:/fsx/analysis_results/ubuntu/hg38/hg005hg007/daylily$ rm [3mresults/day/hg38/other_reports/giabhcr_concordance_mqc.tsv[23mresults/day/hg38/other_reports/giabhcr_concordance_mqc.tsv
[?2004l[?2004h(base) ubuntu@ip-10-0-0-196:/fsx/analysis_results/ubuntu/hg38/hg005hg007/daylily$ rm results/day/hg38/other_reports/giabhcr_concordance_mqc.tsvfind results/ | grep giab | grep _mqc | parallel 'ls -lth {}'[K[C[1P[1P[1P[1P[1@n[1@o[1@r[1@m[1@_[1@C
[?2004l[?2004h(base) ubuntu@ip-10-0-0-196:/fsx/analysis_results/ubuntu/hg38/hg005hg007/daylily$ find results/ | grep norm_C | grep _mqc[1P[1@c
[?2004lresults/day/hg38/other_reports/norm_cov_evenness_combo[01;31m[K_mqc[m[K.tsv
results/day/hg38/other_reports/norm_cov_evenness[01;31m[K_mqc[m[K.tsv
[?2004h(base) ubuntu@ip-10-0-0-196:/fsx/analysis_results/ubuntu/hg38/hg005hg007/daylily$ find results/ | grep norm_c | grep _mqc | parallel 'ls -lth {}'
[?2004l-rw-rw-r-- 1 ubuntu ubuntu 27K Nov 20 21:32 results/day/hg38/other_reports/norm_cov_evenness_combo_mqc.tsv
-rw-rw-r-- 1 ubuntu ubuntu 4.5K Nov 19 08:32 results/day/hg38/other_reports/norm_cov_evenness_mqc.tsv
[?2004h(base) ubuntu@ip-10-0-0-196:/fsx/analysis_results/ubuntu/hg38/hg005hg007/daylily$ find results/ | grep norm_c | grep _mqc | parallel 'ls -lth {}'[C[Krm [3mresults/day/hg38/other_reports/norm_cov_evenness_mqc.tsv[23mresults/day/hg38/other_reports/norm_cov_evenness_mqc.tsv
[?2004l[?2004h(base) ubuntu@ip-10-0-0-196:/fsx/analysis_results/ubuntu/hg38/hg005hg007/daylily$ grep multiqc logs/slurm/multiqc_ff[Kinal_wgs/*
[?2004l[35m[Klogs/slurm/multiqc_final_wgs/multiqc_final_wgs.RIH0_ANA0-HG004-19.1.err[m[K[36m[K:[m[Krule [01;31m[Kmultiqc[m[K_final_wgs:
[35m[Klogs/slurm/multiqc_final_wgs/multiqc_final_wgs.RIH0_ANA0-HG004-19.1.err[m[K[36m[K:[m[K    output: results/day/hg38/reports/DAY_final_[01;31m[Kmultiqc[m[K.html
[35m[Klogs/slurm/multiqc_final_wgs/multiqc_final_wgs.RIH0_ANA0-HG004-19.1.err[m[K[36m[K:[m[K    benchmark: results/day/hg38/benchmarks/DAY_all.final_[01;31m[Kmultiqc[m[K.bench.tsv
[35m[Klogs/slurm/multiqc_final_wgs/multiqc_final_wgs.RIH0_ANA0-HG004-19.1.err[m[K[36m[K:[m[K    reason: Missing output files: results/day/hg38/reports/DAY_final_[01;31m[Kmultiqc[m[K.html
[35m[Klogs/slurm/multiqc_final_wgs/multiqc_final_wgs.RIH0_ANA0-HG004-19.1.err[m[K[36m[K:[m[K        [01;31m[Kmultiqc[m[K -f          --config config/external_tools/[01;31m[Kmultiqc[m[K_header.yaml          --config  config/external_tools/[01;31m[Kmultiqc[m[K_config.yaml          --filename results/day/hg38/reports/DAY_final_[01;31m[Kmultiqc[m[K.html         -i 'Final Multiqc Report'         -b 'Git Info branch:* main tag:yo hash:e61377b'         $(dirname results/day/hg38/logs/report_components_aggregated.done results/day/hg38/other_reports/rules_benchmark_data_mqc.tsv )/../ > results/day/hg38/reports/logs/all__mqc_fin_a.log 2>&1;
[35m[Klogs/slurm/multiqc_final_wgs/multiqc_final_wgs.RIH0_ANA0-HG004-19.1.err[m[K[36m[K:[m[K        ls -lt results/day/hg38/reports/DAY_final_[01;31m[Kmultiqc[m[K.html;
[35m[Klogs/slurm/multiqc_final_wgs/multiqc_final_wgs.RIH0_ANA0-HG004-19.1.out[m[K[36m[K:[m[K-rw-rw-r-- 1 ubuntu ubuntu 11441320 Nov 20 22:37 results/day/hg38/reports/DAY_final_[01;31m[Kmultiqc[m[K.html
[35m[Klogs/slurm/multiqc_final_wgs/multiqc_final_wgs.RIH0_ANA0-HG005-19.1.err[m[K[36m[K:[m[Krule [01;31m[Kmultiqc[m[K_final_wgs:
[35m[Klogs/slurm/multiqc_final_wgs/multiqc_final_wgs.RIH0_ANA0-HG005-19.1.err[m[K[36m[K:[m[K    output: results/day/hg38/reports/DAY_final_[01;31m[Kmultiqc[m[K.html
[35m[Klogs/slurm/multiqc_final_wgs/multiqc_final_wgs.RIH0_ANA0-HG005-19.1.err[m[K[36m[K:[m[K    benchmark: results/day/hg38/benchmarks/DAY_all.final_[01;31m[Kmultiqc[m[K.bench.tsv
[35m[Klogs/slurm/multiqc_final_wgs/multiqc_final_wgs.RIH0_ANA0-HG005-19.1.err[m[K[36m[K:[m[K    reason: Missing output files: results/day/hg38/reports/DAY_final_[01;31m[Kmultiqc[m[K.html, results/day/hg38/benchmarks/DAY_all.final_[01;31m[Kmultiqc[m[K.bench.tsv
[35m[Klogs/slurm/multiqc_final_wgs/multiqc_final_wgs.RIH0_ANA0-HG005-19.1.err[m[K[36m[K:[m[K        ( env bash workflow/scripts/create_final_mqc_report.sh 'results/day/hg38/reports/' 'DAY_final_[01;31m[Kmultiqc[m[K.html'         '/fsx/analysis_results/ubuntu/hg38/hg005hg007/daylily/config/external_tools/[01;31m[Kmultiqc[m[K.yaml' '/fsx/analysis_results/ubuntu/hg38/hg005hg007/daylily/config/external_tools/[01;31m[Kmultiqc[m[K_final.yaml'         '/fsx/analysis_results/ubuntu/hg38/hg005hg007/daylily/config/external_tools/[01;31m[Kmultiqc[m[K_blank.yaml' 'yo' '677105a'         '* main' '' 'RIH0'         'ANA0-HG005-19' 'RIH0_ANA0-HG005-19'         ' ' "$url_root"         'results/day/hg38/'          "none" "hg38" 'results/day/hg38/reports/logs/all_mqc_fin_b.log' "$url_root2"  >> results/day/hg38/reports/logs/all__mqc_fin_a.log  2>&1) || echo "MQC PROBLEM";
[35m[Klogs/slurm/multiqc_final_wgs/multiqc_final_wgs.RIH0_ANA0-HG005-19.1.err[m[K[36m[K:[m[K        ls -lt results/day/hg38/reports/DAY_final_[01;31m[Kmultiqc[m[K.html;
[35m[Klogs/slurm/multiqc_final_wgs/multiqc_final_wgs.RIH0_ANA0-HG005-19.1.out[m[K[36m[K:[m[K-rw-rw-r-- 1 ubuntu ubuntu 6325806 Nov 19 09:02 results/day/hg38/reports/DAY_final_[01;31m[Kmultiqc[m[K.html
[?2004h(base) ubuntu@ip-10-0-0-196:/fsx/analysis_results/ubuntu/hg38/hg005hg007/daylily$ conda actib[Kvate mqc
[?2004l[?2004h(mqc) ubuntu@ip-10-0-0-196:/fsx/analysis_results/ubuntu/hg38/hg005hg007/daylily$ [3mmultiqc -f          --config config/external_tools/multiqc_header.yaml          --config  config/external_tools/multiqc_config.yaml          --filename results/day/hg38/reports/DAY_final_multiq[23m[3mc[23m[3m.html         -i 'Final Multiqc Report'         -b 'Git Info branch:* main tag:yo hash:e61377b'         $(dirname results/day/hg38/logs/report_components_aggregated.done results/day/hg38/other_reports/rules_benchmark_data_mqc.tsv )/../ > results/day/hg38/reports/logs/all__[23m[3mm[23m[3mqc_fin_a.log 2>&1;[23mMM[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Cmultiqc -f          --config config/external_tools/multiqc_header.yaml          --config  config/external_tools/multiqc_config.yaml          --filename results/day/hg38/reports/DAY_final_multiqc.html         -i 'Final Multiqc Report'         -b 'Git Info branch:* main tag:yo hash:e61377b'         $(dirname results/day/hg38/logs/report_components_aggregated.done results/day/hg38/other_reports/rules_benchmark_data_mqc.tsv )/../ > results/day/hg38/reports/logs/all__mqc_fin_a.log 2>&1;
[?2004l[?2004h(mqc) ubuntu@ip-10-0-0-196:/fsx/analysis_results/ubuntu/hg38/hg005hg007/daylily$ 
[?2004l[?2004h(mqc) ubuntu@ip-10-0-0-196:/fsx/analysis_results/ubuntu/hg38/hg005hg007/daylily$ 
[?2004l[?2004h(mqc) ubuntu@ip-10-0-0-196:/fsx/analysis_results/ubuntu/hg38/hg005hg007/daylily$ multiqc --help | more
[?2004l                                                                                                                                                                                                                                                                                  
 /// MultiQC 🔍 v1.25.1                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                  
 Usage: multiqc [OPTIONS] [ANALYSIS DIRECTORY]                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                  
 MultiQC aggregates results from bioinformatics analyses across many samples into a single report.                                                                                                                                                                                
 It searches a given directory for analysis logs and compiles an HTML report. It's a general use tool, perfect for summarising the output from numerous bioinformatics tools.                                                                                                     
 To run, supply with one or more directory to scan for analysis results. For example, to run in the current working directory, use 'multiqc .'                                                                                                                                    
                                                                                                                                                                                                                                                                                  
╭─ Main options ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ --force            -f  Overwrite any existing reports                                                                                                                                                                                                                          │
│ --config           -c  Specific config file to load, after those in MultiQC dir / home dir / working dir. (PATH)                                                                                                                                                               │
│ --cl-config            Specify MultiQC config YAML on the command line (TEXT)                                                                                                                                                                                                  │
│ --filename         -n  Report filename. Use 'stdout' to print to standard out. (TEXT)                                                                                                                                                                                          │
│ --outdir           -o  Create report in the specified output directory. (TEXT)                                                                                                                                                                                                 │
│ --ignore           -x  Ignore analysis files (GLOB EXPRESSION)                                                                                                                                                                                                                 │
│ --ignore-samples       Ignore sample names (GLOB EXPRESSION)                                                                                                                                                                                                                   │
│ --ignore-symlinks      Ignore symlinked directories and files                                                                                                                                                                                                                  │
│ --file-list        -l  Supply a file containing a list of file paths to be searched, one per row                                                                                                                                                                               │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─ Choosing modules to run ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ --module   -m  Use only this module. Can specify multiple times. (MODULE NAME)                                                                                                                                                                                                 │
│ --exclude  -e  Do not use this module. Can specify multiple times. (MODULE NAME)                                                                                                                                                                                               │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─ Sample handling ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ --dirs           -d   Prepend directory to sample names                                                                                                                                                                                                                        │
[3m--More--[23m│ --dirs-depth     -dd  Prepend n directories to sample names. Negative number to take from start of path. (INTEGER)                                                                                                                                                             │
│ --fullnames      -s   Do not clean the sample names (leave as full file name)                                                                                                                                                                                                  │
│ --fn_as_s_name        Use the log filename as the sample name                                                                                                                                                                                                                  │
│ --replace-names       TSV file to rename sample names during report generation (PATH)                                                                                                                                                                                          │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─ Report customisation ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ --title            -i  Report title. Printed as page header, used for filename if not otherwise specified. (TEXT)                                                                                                                                                              │
│ --comment          -b  Custom comment, will be printed at the top of the report. (TEXT)                                                                                                                                                                                        │
│ --template         -t  Report template to use. (default|gathered|geo|sections|simple)                                                                                                                                                                                          │
│ --sample-names         TSV file containing alternative sample names for renaming buttons in the report (PATH)                                                                                                                                                                  │
│ --sample-filters       TSV file containing show/hide patterns for the report (PATH)                                                                                                                                                                                            │
│ --custom-css-file      Custom CSS file to add to the final report (PATH)                                                                                                                                                                                                       │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─ Output files ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ --flat                    -fp  Use only flat plots (static images)                                                                                                                                                                                                             │
│ --interactive             -ip  Use only interactive plots (in-browser Javascript)                                                                                                                                                                                              │
│ --export                  -p   Export plots as static images in addition to the report                                                                                                                                                                                         │
│ --data-dir/--no-data-dir       Force the parsed data directory to be created.                                                                                                                                                                                                  │
│ --data-format             -k   Output parsed data in a different format. (tsv|csv|json|yaml)                                                                                                                                                                                   │
│ --zip-data-dir            -z   Compress the data directory.                                                                                                                                                                                                                    │
│ --no-report                    Do not generate a report, only export data and plots                                                                                                                                                                                            │
│ --pdf                          Creates PDF report with the 'simple' template. Requires Pandoc to be installed.                                                                                                                                                                 │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─ MultiQC behaviour ───────────────────────────────────────────────────────────────────────────────────────�