version: 1.2
workflows:
 - subclass: WDL
   primaryDescriptorPath: /definitions/immuno.wdl
   name: immuno
   authors:
    - orcid: 0000-0003-4266-6700 #chrisamiller
    - orcid: 0000-0002-6388-446X #malachig
    - orcid: 0000-0003-4378-7328 #susannasiebert
    - orcid: 0000-0002-0577-4705 #tmooney
    - orcid: 0000-0001-6293-4632 #sridhar0605
    - orcid: 0009-0002-2565-0774 #johnegarza
    - orcid: 0000-0001-7547-5789 #jasonwalker80
    - orcid: 0000-0003-1928-7139 #zlskidmore
    - orcid: 0000-0002-7648-1360 #bryanfisk
    - orcid: 0000-0003-0944-3126 #acoffman
    - orcid: 0000-0002-2584-5320 #jhundal
    - orcid: 0000-0002-9704-408X #Matthew-Mosior
    - orcid: 0000-0002-3024-6891 #apaul7
    - name: John Maruska #johnmaruska
    - name: Layth Aljorani #Layth17
    - name: Sai Mukund Ramakrishnan #saimukund20
    - name: Feiyu Du #dufeiyu
    - name: Saad Khan #smk5g5
    - name: Samuel Peters #sam16711
    - name: Agata Gruszczynska #GruA
    - name: Gue Su Chang #guesu, gschang
    - name: Irenaeus Chan #IrenaeusChan
    - name: Chad Tomlinson #chad388
