#Pull key information from metadata YAML files

# --------------- Tumor DNA input data files and meta-data --------------
immuno.tumor_sequence:
- sequence:
    fastq1: ""
    fastq2: ""
  readgroup: "@RG\tID:1\tPU:\tSM:\tLB:\tPL:Illumina\tCN:"
immuno.tumor_sample_name: ""

# --------------- Normal DNA input data files and meta-data --------------
immuno.normal_sequence:
- sequence:
    fastq1: ""
    fastq2: ""
  readgroup: "@RG\tID:2\tPU:\tSM:\tLB:\tPL:Illumina\tCN:"
immuno.normal_sample_name: ""

# ------------- Tumor RNA sample input data files and meta-data -----------------
immuno.rna_sequence:
- sequence:
    fastq1: ""
    fastq2: ""
  readgroup: "ID:3\tPU:\tSM:\tLB:\tPL:Illumina\tCN:"
immuno.sample_name: ""
immuno.strand: ""

# ------------- CLE validated variants for intersection/filtering --------------------
#Not applicable to this case since sequencing was done outside WASHU CLE lab and we did not receive a VCF from Tempus
#immuno.validated_variants: ""
#immuno.validated_variants_tbi: ""

# ------------- Reference genome for DNA-seq alignments ---------------
immuno.reference: "gs://griffith-lab-workflow-inputs/human_GRCh38_ens105/aligner_indices/bwamem2_2.2.1/all_sequences.fa"
immuno.reference_fai: "gs://griffith-lab-workflow-inputs/human_GRCh38_ens105/aligner_indices/bwamem2_2.2.1/all_sequences.fa.fai"
immuno.reference_dict: "gs://griffith-lab-workflow-inputs/human_GRCh38_ens105/aligner_indices/bwamem2_2.2.1/all_sequences.dict"
immuno.reference_alt: "gs://griffith-lab-workflow-inputs/human_GRCh38_ens105/aligner_indices/bwamem2_2.2.1/all_sequences.fa.alt"
immuno.reference_amb: "gs://griffith-lab-workflow-inputs/human_GRCh38_ens105/aligner_indices/bwamem2_2.2.1/all_sequences.fa.amb"
immuno.reference_ann: "gs://griffith-lab-workflow-inputs/human_GRCh38_ens105/aligner_indices/bwamem2_2.2.1/all_sequences.fa.ann"
immuno.reference_bwt: "gs://griffith-lab-workflow-inputs/human_GRCh38_ens105/aligner_indices/bwamem2_2.2.1/all_sequences.fa.bwt.2bit.64"
immuno.reference_pac: "gs://griffith-lab-workflow-inputs/human_GRCh38_ens105/aligner_indices/bwamem2_2.2.1/all_sequences.fa.pac"
immuno.reference_0123: "gs://griffith-lab-workflow-inputs/human_GRCh38_ens105/aligner_indices/bwamem2_2.2.1/all_sequences.fa.0123"
immuno.synonyms_file: "gs://griffith-lab-workflow-inputs/human_GRCh38_ens105/reference_genome/chromAlias.ensembl.txt"

# ------------- Reference files and settings for STAR alignment and STAR-fusion calling
immuno.star_fusion_genome_dir_zip: "gs://griffith-lab-workflow-inputs/human_GRCh38_ens105/aligner_indices/star-fusion_1.10.1_index.zip"
immuno.examine_coding_effect: true
immuno.fusioninspector_mode: "validate"
immuno.cdna_fasta: "gs://griffith-lab-workflow-inputs/human_GRCh38_ens105/rna_seq_annotation/Homo_sapiens.GRCh38.cdna.all.fa.gz"
immuno.agfusion_database: "gs://griffith-lab-workflow-inputs/human_GRCh38_ens105/agfusion_1.3_database/agfusion.homo_sapiens.105.db"
immuno.agfusion_annotate_noncanonical: true
immuno.min_ffpm_level: 0.025

# ------------- RNA transcript annotations ------------
immuno.ribosomal_intervals: "gs://griffith-lab-workflow-inputs/human_GRCh38_ens105/rna_seq_annotation/Homo_sapiens.GRCh38.105.ribo_intervals"
immuno.gene_transcript_lookup_table: "gs://griffith-lab-workflow-inputs/human_GRCh38_ens105/rna_seq_annotation/ensembl105.transcriptToGene.tsv"
immuno.kallisto_index: "gs://griffith-lab-workflow-inputs/human_GRCh38_ens105/rna_seq_annotation/Homo_sapiens.GRCh38.cdna.all.fa.kallisto.idx"
immuno.refFlat: "gs://griffith-lab-workflow-inputs/human_GRCh38_ens105/rna_seq_annotation/Homo_sapiens.GRCh38.105.refFlat.txt"
immuno.reference_annotation: "gs://griffith-lab-workflow-inputs/human_GRCh38_ens105/rna_seq_annotation/Homo_sapiens.GRCh38.105.gtf"

# ------------ RNA trimming settings ---------------- 
immuno.trimming_adapter_min_overlap: 7
immuno.trimming_adapter_trim_end: RIGHT
immuno.trimming_adapters: "gs://griffith-lab-workflow-inputs/human_GRCh38_ens105/misc/illumina_multiplex.fa"
immuno.trimming_max_uncalled: 300
immuno.trimming_min_readlength: 25

# ------------- Baits and targets for exome reagent (94b23d66f667472690a7ee165e2037b6 = "xGen Lockdown Exome Panel v1)"
immuno.bait_intervals: "gs://griffith-lab-workflow-inputs/human_GRCh38_ens105/capture_reagents/IDT_xGen_Lockdown_Exome_v1.baits.interval_list"
immuno.target_intervals: "gs://griffith-lab-workflow-inputs/human_GRCh38_ens105/capture_reagents/IDT_xGen_Lockdown_Exome_v1.targets.interval_list"

# ------------- Miscellaneous other know variant files
immuno.docm_vcf: "gs://griffith-lab-workflow-inputs/human_GRCh38_ens105/known_variants/docm.vcf.gz"
immuno.docm_vcf_tbi: "gs://griffith-lab-workflow-inputs/human_GRCh38_ens105/known_variants/docm.vcf.gz.tbi"
immuno.omni_vcf: "gs://griffith-lab-workflow-inputs/human_GRCh38_ens105/known_variants/omni25-ld-pruned-20000-2000-0.5-annotated.wchr.sites_only.b38.autosomes_only.vcf.gz"
immuno.omni_vcf_tbi: "gs://griffith-lab-workflow-inputs/human_GRCh38_ens105/known_variants/omni25-ld-pruned-20000-2000-0.5-annotated.wchr.sites_only.b38.autosomes_only.vcf.gz.tbi"
immuno.somalier_vcf: "gs://griffith-lab-workflow-inputs/human_GRCh38_ens105/known_variants/GRC-human-build38_gnomad_exome_common_snps.vcf"

# ------------- Variant annotation VEP cache --------------------
immuno.vep_cache_dir_zip: "gs://griffith-lab-workflow-inputs/human_GRCh38_ens105/vep_cache.zip"

# ---------------- Sites to ignore/treat specially during base quality score recalibration after alignemt as per GATK best practices -------------------
immuno.bqsr_known_sites:
- "gs://griffith-lab-workflow-inputs/human_GRCh38_ens105/known_variants/Homo_sapiens_assembly38.dbsnp138.vcf.gz"
- "gs://griffith-lab-workflow-inputs/human_GRCh38_ens105/known_variants/Homo_sapiens_assembly38.known_indels.vcf.gz"
- "gs://griffith-lab-workflow-inputs/human_GRCh38_ens105/known_variants/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz"
immuno.bqsr_known_sites_tbi:
- "gs://griffith-lab-workflow-inputs/human_GRCh38_ens105/known_variants/Homo_sapiens_assembly38.dbsnp138.vcf.gz.tbi"
- "gs://griffith-lab-workflow-inputs/human_GRCh38_ens105/known_variants/Homo_sapiens_assembly38.known_indels.vcf.gz.tbi"
- "gs://griffith-lab-workflow-inputs/human_GRCh38_ens105/known_variants/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz.tbi"

# -------------------- Regions used for QC reporting on coverage of known variants and clinically relevant genes -------------------
immuno.per_base_intervals:
- file: "gs://griffith-lab-workflow-inputs/human_GRCh38_ens105/qc_regions/clinvar.interval_list"
  label: clinvar
immuno.per_target_intervals:
- file: "gs://griffith-lab-workflow-inputs/human_GRCh38_ens105/qc_regions/acmg_genes.interval_list"
  label: acmg_genes
immuno.picard_metric_accumulation_level: LIBRARY

#--------------------- VEP variant annotation settings ----------------------
immuno.vep_ensembl_species: homo_sapiens
immuno.vep_ensembl_assembly: GRCh38
immuno.gnomad_field_name: gnomADe_AF
immuno.vep_custom_annotations:
- method: exact
  force_report_coordinates: true
  annotation:
    file: "gs://griffith-lab-workflow-inputs/human_GRCh38_ens105/known_variants/gnomad_fixed_b38_exome.vcf.gz"
    secondary_files:
    - "gs://griffith-lab-workflow-inputs/human_GRCh38_ens105/known_variants/gnomad_fixed_b38_exome.vcf.gz.tbi"
    data_format: vcf
    name: gnomADe
    vcf_fields:
    - AF
    - AF_AFR
    - AF_AMR
    - AF_ASJ
    - AF_EAS
    - AF_FIN
    - AF_NFE
    - AF_OTH
    - AF_SAS
    gnomad_filter: true
    check_existing: true
immuno.vep_ensembl_version: '105'

# ---------------------- How much to divide genome into pieces for some compute intensive steps --------------------
immuno.scatter_count: 50

# ---------------------- Variant table report generation options --------------------
immuno.vep_to_table_fields:
- Consequence
- SYMBOL
- Feature_type
- Feature
- HGVSc
- HGVSp
- cDNA_position
- CDS_position
- Protein_position
- Amino_acids
- Codons
- HGNC_ID
- Existing_variation
- gnomADe_AF
- CLIN_SIG
- SOMATIC
- PHENO
- clinvar_CLINSIGN
- clinvar_PHENOTYPE
- clinvar_SCORE
- clinvar_RCVACC
- clinvar_TESTEDINGTR
- clinvar_PHENOTYPELIST
- clinvar_NUMSUBMIT
- clinvar_GUIDELINES
#note that if you are comparing to a set of known variants (e.g. from a CLIA/CAP lab, add "VALIDATED" to the following list
immuno.variants_to_table_fields:
- CHROM
- POS
- REF
- ALT
- set
immuno.variants_to_table_genotype_fields:
- GT
- AD
- AF
- DP

# --------------------- pVACtools settings ----------------------
immuno.prediction_algorithms:
- all
immuno.epitope_lengths_class_i:
- 8
- 9
- 10
- 11
immuno.epitope_lengths_class_ii:
- 12
- 13
- 14
- 15
- 16
- 17
- 18
immuno.binding_threshold: 500
immuno.minimum_fold_change: 0
immuno.top_score_metric: median
immuno.downstream_sequence_length: 100
#immuno.net_chop_method: cterm
immuno.netmhc_stab: false
immuno.pvacseq_threads: 8
immuno.maximum_transcript_support_level: 1
immuno.normal_vaf: 0.01
immuno.tdna_vaf: 0.1
immuno.trna_vaf: 0.1
immuno.normal_cov: 30
immuno.tdna_cov: 30
immuno.hla_source_mode: consensus
immuno.iedb_retries: 3
immuno.pvacfuse_keep_tmp_files: true
#immuno.blastp_db: refseq_select_prot

#pvacseq v4 modifications
immuno.run_reference_proteome_similarity: true
immuno.peptide_fasta: "gs://griffith-lab-workflow-inputs/human_GRCh38_ens105/rna_seq_annotation/Homo_sapiens.GRCh38.pep.all.fa.gz"
immuno.aggregate_inclusion_binding_threshold: 1500
immuno.allele_specific_anchors: true
immuno.problematic_amino_acids:
- C

# ------------------ If you have clinical or otherwise known HLA typing, include here and it will be integrated with Optitype calls ---------------
# Source of HLA types for this sample: Histogenetics typing
# Resolve any ambiguous alleles (https://hml.nmdp.org/MacUI/) -> Decode MAC option.

#immuno.clinical_mhc_classI_alleles:
#- HLA-A*02:01
#- HLA-A*26:01
#- HLA-B*15:01
#- HLA-B*40:02
#- HLA-C*03:03
#- HLA-C*03:04
#immuno.clinical_mhc_classII_alleles:
#- DRB1*01:01
#- DRB1*15:01
#- DRB5*01:01
#- DQB1*05:01
#- DQB1*06:02
#- DQA1*01:01
#- DQA1*01:02
#- DPB1*04:01
#- DPB1*04:02
#- DPA1*01:03

# -------------- Intervals to use during GATK germline variant calling -----------------
immuno.gatk_haplotypecaller_intervals:
- - chr1
- - chr2
- - chr3
- - chr4
- - chr5
- - chr6
- - chr7
- - chr8
- - chr9
- - chr10
- - chr11
- - chr12
- - chr13
- - chr14
- - chr15
- - chr16
- - chr17
- - chr18
- - chr19
- - chr20
- - chr21
- - chr22
- - chrX
- - chrY

# ------------- miscellaneous settings ------------------
immuno.summary_intervals: []
immuno.gvcf_gq_bands: []

# ------------- fda qc report values --------------------
immuno.reference_genome_name: "Custom GRCh38 https://zenodo.org/record/4684553"
immuno.dna_sequencing_platform: "Illumina"
immuno.dna_sequencing_instrument: "NovaSeq 6000"
immuno.dna_sequencing_kit: "NovaSeq 6000 S4 Reagent Kit v1.5"
immuno.dna_sequencing_type: "Whole Exome Sequencing"
immuno.dna_single_or_paired_end: "Paired End"
immuno.normal_dna_spike_in_error_rate: "Less than 0.50% for Read 1 and less than 0.75% for Read 2"
immuno.tumor_dna_spike_in_error_rate: "Less than 0.50% for Read 1 and less than 0.75% for Read 2"
immuno.normal_dna_total_dna: "Not provided"
immuno.tumor_dna_total_dna: "Not provided"
immuno.rna_sequencing_platform: "Illumina"
immuno.rna_sequencing_instrument: "NovaSeq 6000"
immuno.rna_sequencing_kit: "RNA Directional Library Prep Kit"
immuno.rna_sequencing_type: "Riboreduction followed by cDNA capture sequencing"
immuno.rna_single_or_paired_end: "Paired end"
immuno.rna_spike_in_error_rate: "Not provided"
immuno.rna_total_rna: "Not provided"
immuno.rna_rin_score: "Not provided"
immuno.rna_freq_normalization_method: "TPM"
immuno.rna_annotation_file: "http://ftp.ensembl.org/pub/release-105/gtf/homo_sapiens/Homo_sapiens.GRCh38.105.gtf.gz"

