wf.vcf: gs://griffith-lab-cromwell/cromwell-executions/detectVariants/1196c484-24d9-4ab1-9778-a5b22c37c5a0/call-annotatedFilterIndex/test.vcf.gz
wf.tsv: gs://griffith-lab-cromwell/cromwell-executions/wf/c6f7dae6-104c-4777-843a-e2e8765ac7bb/call-variantsToTable/variants.tsv
wf.vep_fields:
  - Consequence
  - SYMBOL
  - Feature_type
  - Feature
  - HGVSc
  - HGVSp
  - cDNA_position
  - CDS_position
  - Protein_position
  - Amino_acids
  - Codons
  - HGNC_ID
  - Existing_variation
  - gnomADe_AF
  - CLIN_SIG
  - SOMATIC
  - PHENO
  - clinvar_CLINSIGN
  - clinvar_PHENOTYPE
  - clinvar_SCORE
  - clinvar_RCVACC
  - clinvar_TESTEDINGTR
  - clinvar_PHENOTYPELIST
  - clinvar_NUMSUBMIT
  - clinvar_GUIDELINES
