bam: gs://griffith-lab-cromwell/cromwell-executions/rnaseq/b701ca54-4f0b-4498-9d52-24d502b64ef2/call-markDup/MarkedSorted.bam
bam_bai: gs://griffith-lab-cromwell/cromwell-executions/rnaseq/b701ca54-4f0b-4498-9d52-24d502b64ef2/call-markDup/MarkedSorted.bam.bai
reference: gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes.fa
reference_fai: gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes.fa.fai
reference_dict: gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes.dict
