wf.reference: gs://griffith-lab-cromwell/input_data/maruska/2021-05-10/somatic_inputs/hla_and_brca_genes.fa
wf.reference_dict: gs://griffith-lab-cromwell/input_data/maruska/2021-05-10/somatic_inputs/hla_and_brca_genes.dict
wf.reference_fai: gs://griffith-lab-cromwell/input_data/maruska/2021-05-10/somatic_inputs/hla_and_brca_genes.fa.fai

wf.vcf: gs://griffith-lab-cromwell/cromwell-executions/wf/734853bb-327b-41a4-828e-c355ee806bc2/call-vep/test.vcf.gz_annotated.vcf

wf.bam: gs://griffith-lab-cromwell/cromwell-executions/alignmentExome/1b955790-a3c1-4cf2-8371-bf415f3525a1/call-alignment/sequenceToBqsr/c6ccbfef-2a84-4f50-be00-396017d1be0c/call-applyBqsr/H_NJ-HCC1395-HCC1395.bam
wf.bam_bai: gs://griffith-lab-cromwell/cromwell-executions/alignmentExome/1b955790-a3c1-4cf2-8371-bf415f3525a1/call-alignment/sequenceToBqsr/c6ccbfef-2a84-4f50-be00-396017d1be0c/call-indexBam/H_NJ-HCC1395-HCC1395.bam.bai

wf.sample: H_NJ-HCC1395-HCC1395
