wf.bam: gs://griffith-lab-cromwell/cromwell-executions/alignmentExome/988f1110-8f6c-4b30-a6e4-dc76288fd88e/call-alignment/sequenceToBqsr/053d0207-dd66-42d8-93f8-290b6e831e9a/call-applyBqsr/H_NJ-HCC1395-HCC1395.bam.bam
wf.bam_bai: gs://griffith-lab-cromwell/cromwell-executions/alignmentExome/988f1110-8f6c-4b30-a6e4-dc76288fd88e/call-alignment/sequenceToBqsr/053d0207-dd66-42d8-93f8-290b6e831e9a/call-indexBam/H_NJ-HCC1395-HCC1395.bam.bam.bai
wf.reference: gs://griffith-lab-cromwell/input_data/maruska/2021-05-10/somatic_inputs/hla_and_brca_genes.fa
wf.reference_fai: gs://griffith-lab-cromwell/input_data/maruska/2021-05-10/somatic_inputs/hla_and_brca_genes.fa.fai
wf.reference_dict: gs://griffith-lab-cromwell/input_data/maruska/2021-05-10/somatic_inputs/hla_and_brca_genes.dict
wf.bait_intervals: gs://griffith-lab-cromwell/input_data/maruska/2021-05-10/somatic_inputs/hla_and_brca_genes_bait.interval_list
wf.target_intervals: gs://griffith-lab-cromwell/input_data/maruska/2021-05-10/somatic_inputs/hla_and_brca_genes_target.interval_list
wf.metric_accumulation_level: "ALL_READS"
wf.per_target_coverage: false
wf.per_base_coverage: false
wf.output_prefix: "roi"
