wf.extractHlaAlleles.allele_file: gs://griffith-lab-cromwell/cromwell-executions/immuno/b416797b-1f04-4826-8df9-89865102c21a/call-germline/germlineExomeHlaTyping/ac1477b8-0ffc-48e8-a057-723a4bb83f06/call-optitype/optitype_result.tsv
