wf.reference: gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes.fa
wf.reference_fai: gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes.fa.fai
wf.reference_dict: gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes.dict

wf.tumor_bam: gs://griffith-lab-cromwell/cromwell-executions/wf/8dc1181b-ad18-48b5-9cd2-cbeea78cad2d/call-indexBam/tumor.bam.bam
wf.tumor_bam_bai: gs://griffith-lab-cromwell/cromwell-executions/wf/8dc1181b-ad18-48b5-9cd2-cbeea78cad2d/call-indexBam/tumor.bam.bam.bai

wf.normal_bam: gs://griffith-lab-cromwell/cromwell-executions/wf/f3313113-bef0-4589-a1af-08260a67591c/call-indexBam/normal.bam.bam
wf.normal_bam_bai: gs://griffith-lab-cromwell/cromwell-executions/wf/f3313113-bef0-4589-a1af-08260a67591c/call-indexBam/normal.bam.bam.bai

wf.non_wgs: true
