wf.pvacseq.input_vcf_tbi: gs://griffith-lab-cromwell/cromwell-executions/immuno/b3a778ab-2818-41aa-bda5-ab3b1eb72454/call-pvacseq/pvacseq/54505a50-4369-4ee1-b2fc-a34359ea2874/call-index/annotated.expression.vcf.gz.tbi
wf.pvacseq.input_vcf: gs://griffith-lab-cromwell/cromwell-executions/immuno/b3a778ab-2818-41aa-bda5-ab3b1eb72454/call-pvacseq/pvacseq/54505a50-4369-4ee1-b2fc-a34359ea2874/call-index/annotated.expression.vcf.gz
wf.pvacseq.phased_proximal_variants_vcf: gs://griffith-lab-cromwell/cromwell-executions/phaseVcf/fc920dc4-51b0-4093-b09e-9197b830fea6/call-bgzipAndIndexPhasedVcf/bgzipAndIndex/7524b032-41aa-4587-a0bf-b6ba9a111738/call-index/phased.vcf.gz
wf.pvacseq.phased_proximal_variants_vcf_tbi: gs://griffith-lab-cromwell/cromwell-executions/phaseVcf/fc920dc4-51b0-4093-b09e-9197b830fea6/call-bgzipAndIndexPhasedVcf/bgzipAndIndex/7524b032-41aa-4587-a0bf-b6ba9a111738/call-index/phased.vcf.gz.tbi
wf.pvacseq.sample_name: 'H_NJ-HCC1395-HCC1395'
wf.pvacseq.normal_sample_name: 'H_NJ-HCC1395-HCC1395_BL'
wf.pvacseq.alleles:
  - "HLA-A*02:13"
  - "HLA-A*29:02"
  - "HLA-B*45:01"
  - "HLA-B*45:01"
  - "HLA-C*06:02"
  - "HLA-C*06:02"
wf.pvacseq.prediction_algorithms:
- NetMHC
