wf.reference: gs://griffith-lab-cromwell/input_data/maruska/2021-05-10/somatic_inputs/hla_and_brca_genes.fa
wf.reference_fai: gs://griffith-lab-cromwell/input_data/maruska/2021-05-10/somatic_inputs/hla_and_brca_genes.fa.fai
wf.reference_dict: gs://griffith-lab-cromwell/input_data/maruska/2021-05-10/somatic_inputs/hla_and_brca_genes.dict
wf.vcf: gs://griffith-lab-cromwell/cromwell-executions/immuno/2bcdc58f-15d0-4a55-832e-6748f4dbb4ac/call-somatic/somaticExome/26844119-6d35-4008-927f-cdb3c6f77834/call-detectVariants/detectVariants/ae396831-6acf-4692-b800-eb4f0ba9ba38/call-annotatedFilterIndex/annotated_filtered.vcf.gz
wf.vcf_tbi: gs://griffith-lab-cromwell/cromwell-executions/immuno/2bcdc58f-15d0-4a55-832e-6748f4dbb4ac/call-somatic/somaticExome/26844119-6d35-4008-927f-cdb3c6f77834/call-detectVariants/detectVariants/ae396831-6acf-4692-b800-eb4f0ba9ba38/call-annotatedFilterIndex/annotated_filtered.vcf.gz.tbi
wf.output_vcf_basename: somatic_tumor_only
wf.samples_to_include:
  - H_NJ-HCC1395-HCC1395
