wf.sequenceAlignAndTag.unaligned:
  sequence:
    bam: gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/unaligned_subset_bams/normal/2895499331.bam
  readgroup: "@RG\tID:2895499331\tPU:H7HY2CCXX.3\tSM:H_NJ-HCC1395-HCC1395_BL\tLB:H_NJ-HCC1395-HCC1395_BL-lg21-lib1\tPL:Illumina\tCN:WUGSC"

wf.sequenceAlignAndTag.reference: gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes.fa
wf.sequenceAlignAndTag.reference_alt: gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes.fa.alt
wf.sequenceAlignAndTag.reference_amb: gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes.fa.amb
wf.sequenceAlignAndTag.reference_ann: gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes.fa.ann
wf.sequenceAlignAndTag.reference_bwt: gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes.fa.bwt
wf.sequenceAlignAndTag.reference_pac: gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes.fa.pac
wf.sequenceAlignAndTag.reference_sa: gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes.fa.sa
