wf.reads1: gs://griffith-lab-test-immuno-pipeline/cromwell-executions/immuno/e521dde0-1fb9-4790-ab5e-41f7b5f3f17c/call-rnaseq/rnaseq/d512554f-ea37-4675-a763-b38ddae42c64/call-ScatterAt51_13/shard-1/ScatterAt51_13/825bc438-dede-4dd7-8f84-6c3f92eeba71/call-ScatterAt52_15/shard-1/ScatterAt52_15/0407c171-79f0-4de1-a4ef-d62dafd7cba2/call-bamToTrimmedFastqAndHisatAlignments/shard-0/bamToTrimmedFastqAndHisatAlignments/060f6b02-8bd2-4758-b06a-416fbb5fb1b4/call-sequenceToFastqRna/glob-9c2215252fd6e4c814b0acffb5de10e9/read1.fastq.gz

wf.reads2: gs://griffith-lab-test-immuno-pipeline/cromwell-executions/immuno/e521dde0-1fb9-4790-ab5e-41f7b5f3f17c/call-rnaseq/rnaseq/d512554f-ea37-4675-a763-b38ddae42c64/call-ScatterAt51_13/shard-1/ScatterAt51_13/825bc438-dede-4dd7-8f84-6c3f92eeba71/call-ScatterAt52_15/shard-1/ScatterAt52_15/0407c171-79f0-4de1-a4ef-d62dafd7cba2/call-bamToTrimmedFastqAndHisatAlignments/shard-0/bamToTrimmedFastqAndHisatAlignments/060f6b02-8bd2-4758-b06a-416fbb5fb1b4/call-sequenceToFastqRna/glob-c660797740fd2a5ad5993a30ce63ffdf/read2.fastq.gz

wf.adapters: gs://griffith-lab-workflow-inputs/human_GRCh38_ens95/misc/illumina_multiplex.fa

wf.adapter_trim_end: RIGHT
wf.adapter_min_overlap: 7
wf.max_uncalled: 300
wf.min_readlength: 25
