wf.vcf: gs://griffith-lab-cromwell/cromwell-executions/detectVariants/1196c484-24d9-4ab1-9778-a5b22c37c5a0/call-annotatedFilterIndex/test.vcf.gz
wf.vcf_tbi: gs://griffith-lab-cromwell/cromwell-executions/detectVariants/1196c484-24d9-4ab1-9778-a5b22c37c5a0/call-annotatedFilterIndex/test.vcf.gz.tbi

wf.reference: gs://griffith-lab-cromwell/input_data/maruska/2021-04-15/gc2560/core/model_data/2887491634/build21f22873ebe0486c8e6f69c15435aa96/all_sequences.fa
wf.reference_fai: gs://griffith-lab-cromwell/input_data/maruska/2021-04-15/gc2560/core/model_data/2887491634/build21f22873ebe0486c8e6f69c15435aa96/all_sequences.fa.fai
wf.reference_dict: gs://griffith-lab-cromwell/input_data/maruska/2021-04-15/gc2560/core/model_data/2887491634/build21f22873ebe0486c8e6f69c15435aa96/all_sequences.dict

wf.fields:
  - CHROM
  - POS
  - REF
  - ALT
  - set
  - AC
  - AF

wf.genotype_fields:
  - GT
  - AD
