vep.cache_dir_zip: gs://griffith-lab-cromwell/input_data/vep.zip
vep.custom_annotations: []
vep.ensembl_assembly: GRCh38
vep.ensembl_species: homo_sapiens
vep.ensembl_version: '95'
vep.plugins:
  - "Frameshift"
  - "Wildtype"
vep.reference: gs://griffith-lab-cromwell/input_data/maruska/2021-05-10/somatic_inputs/hla_and_brca_genes.fa
vep.reference_dict: gs://griffith-lab-cromwell/input_data/maruska/2021-05-10/somatic_inputs/hla_and_brca_genes.dict
vep.reference_fai: gs://griffith-lab-cromwell/input_data/maruska/2021-05-10/somatic_inputs/hla_and_brca_genes.fa.fai
vep.synonyms_file: gs://griffith-lab-cromwell/input_data/maruska/2021-05-10/somatic_inputs/subset_synonyms.txt

vep.vcf: gs://griffith-lab-cromwell/cromwell-executions/wf/ca305da2-b46d-4057-b9ea-635b778d3104/call-indexVcf/test.vcf.gz
