---
pizzazz: "off"  # on or off
profile_name: "global"  # this is over-ridden when profile specific config is included


logs:
    operational:
        top: "logs/ops.log"
        lorm: "logs/lorm.log"
        about: "logs/about.log"
        docker: "logs/docker.log"
    day:
        top: "results/day/logs/day.log"


# example test data
remote_analysis_manifest: ".test_data/data/0.01xwgs_HG002.samplesheet.csv"

# STILL WORKING?
sentieon_liscence_server: "localhost:8990"


# DEORECATED
# you would activate by adding ''' --config rule_action='{"ultraplex_iddnas":"run","kat":"run"}' ''' to the mod-run call
rule_action:
    ultraplex_iddnas: "run"
    kat: "skip"
    concordance: "run"
