---
pizzazz: "off"  # on or off ... never deprecated
profile_name: "global_AWSHPC"  # this is over-ridden when profile specific config is included. DPRECATED?

valid_biome: 'AWSPC'

supporting_dirs: "config/supporting_files/supporting_dirs.yaml"

supporting_data:
    mode: "local_link"  # other options are DPRECATED
    link_point: "resources/fsx/data/"
    link_root: "resources/fsx/"
    link_source: "/fsx/"
    supporting_files_conf: "config/supporting_files/XREF_CODEX_supporting_files.yaml"  # deprecated?
    webdav_point: "resources/fsx/data/"  # deprecated soon
