---
max_table_rows: 1600

num_datasets_plot_limit: 12

decimalPoint_format: "."
thousandsSep_format: ","


# Mosdepoth
exclude_contigs:
  - "*_alt"
  - "*_decoy"
  - "*_random"
  - "chrUn*"
  - "HLA*"
  - "chrM"
  - "MT"
  - "chrEBV"

mosdepth_config:
  show_excluded_debug_logs: true

  exclude_contigs:
    - "*_alt"
    - "*_decoy"
    - "*_random"
    - "chrUn*"
    - "HLA*"
    - "chrM"
    - "MT"
    - "chrEBV"


picard_config:
  insertsize_xmax: 1000
  insertsize_smooth_points: 5


samtools_idxstats_fraction_cutoff: 0.00001


table_columns_placement:
  somename_here_okok:
    DeletedBases: 19

  mosdepth:
    median_coverage: 10
    0_x_pc: 1
    5_x_pc: 5
    10_x_pc: 10
    15_x_pc: 15
    20_x_pc: 20
    25_x_pc: 25
    35_x_pc: 30
    40_x_pc: 40

  alignstats_b:
    InsertSizeMean: 2
    InsertSizeMedian: 3
    InsertSizeMode: 4

  custom_content:
    alignstats_b:
      InsertSizeMean: 2
      InsertSizeMedian: 3
      InsertSizeMode: 4
  custom_data:
    alignstats_b:
      InsertSizeMean: 2
      InsertSizeMedian: 3
      InsertSizeMode: 4

  Picard:
    summed_median: 5
    summed_mean: 6
    mean_coverage: 9

  VerifyBAMID:
    FREEMIX: 30

  Samtools:
    flagstat_total: 20
    reads_mapped: 1223
    properly_paired: 1222
    reads_mapped_percent: 23
    error_rate: 1020


table_columns_visible:
  somename_here_okok: true

  alignstats_b:
    InsertSizeMean: true
    InsertSizeMedian: true
    InsertSizeMode: true
  custom_content:
    alignstats_b:
      InsertSizeMean: true
      InsertSizeMedian: true
      InsertSizeMode: true
  custom_data:
    alignstats_b:
      InsertSizeMean: true
      InsertSizeMedian: true
      InsertSizeMode: true

  mosdepth:
    median_coverage: true
    0_x_pc: true
    1_x_pc: true
    2_x_pc: true
    3_x_pc: true
    4_x_pc: true
    5_x_pc: true
    6_x_pc: true
  Picard:
    mean_coverage: true
    summed_median: true
    summed_mean: true

  VerifyBAMID:
    FREEMIX: true


  FastQC: false

  qualimap: true

  Samtools:
    flagstat_total: false
    reads_mapped: false
    properly_paired: true
    reads_mapped_percent: true
    error_rate: true
