
# These samples were all created via a run of the pipe which
# did not have multiple  aligners or var callers, so
# we truncate the file name back to the sample name core- removing the lane bit


sample_names_replace_regex: True
sample_names_replace:
  "(.*\\/)*(.*_[0|1|2|3|4])(_|tbwa.*)*(\\..*)*": "\\2"

sample_names_ignore:
  - "63"

#extra_fn_clean_exts:
#  - type: regex
#    pattern: "_0\\.?.*|_1\\.?.*|_2\\.?.*|_3\\.?.*|_4\\.?.*|\\.?.*"
