report_header_info:
  - Contact E-mail: "YOUREMAIL@EMAIL.EMAIL"
  - Application Type: "Daylily Report"
  - Project Type: "Application"
  - Sequencing Platform: "SeqPlatformHere"
  - Sequencing Setup: "SeqSetupInfoHere"


