max_table_rows: 1600

num_datasets_plot_limit: 12

decimalPoint_format: "."
thousandsSep_format: ","

# Mosdepoth
exclude_contigs:
  - "*_alt"
  - "*_decoy"
  - "*_random"
  - "chrUn*"
  - "HLA*"
  - "chrM"
  - "MT"
  - "chrEBV"

mosdepth_config:
  show_excluded_debug_logs: True
