#DEV WORK LOGO
custom_logo: "resources/mqcimg/daylilylogo.png"


custom_logo_title: "Daylily MQC Report"

max_table_rows: 2200



fn_ignore_paths:
  - '*/manta_work/*'
  - '/impute/*'
  - '*.md.*'

extra_fn_clean_exts:
  - type: truncate
    pattern: "DBC0"


exclude_modules:
  - slamdunk
  - adapterRemoval
  - rseqc
  - sambamba
  - preseq
  - htseq
  - bbmap
  - fastp
  - varscan2
  - flexbar
  - hicexplorer
  - snpeff
  - biscuit
  - deeptools
  - afterqc
  - bbmap
  - biobambam2
  - biobloomtools
  - biscuit
  - bowtie1
  - bowtie2
  - busco
  - ccs
  - clipandmerge
  - clusterflow
  - conpair
  - cutadapt
  - deeptools
  - disambiguate
  - dragen
  - fgbio
  - flash
  - gatk
  - gffcompare
  - happy
  - hisat2
  - homer
  - ivar
  - jcvi
  - kaiju
  - kallisto
  - kraken
  - leehom
  - lima
  - longranger
  - malt
  - minionqc
  - nanostat
  - ngsderive
  - optitype
  - pangolin
  - prokka
  - pychopper
  - pycoqc
  - qorts
  - rna_seqc
  - rockhopper
  - rseqc
  - salmon
  - samblaster
  - sickle
  - skewer
  - slamdunk
  - snippy
  - snpsplit
  - sortmerna
  - stacks
  - supernova
  - trimmomatic
  - varscan2
  - vep
  - bismark
  - tophat
  - sexdetermine
  - q3c3
  - bclconvert/runino
  - bustools
  - damageprofiler
  - dedup
  - eigenstratdatabasetools
  - featureCounts
  - hicpro
  - hicup
  - hops
  - macs2
  - methylQA
  - mirtop
  - mirtrace
  - mtnucratio
  - multivcfanalyzer
  - odgi
  - phantompeakqualtools

num_datasets_plot_limit: 42

decimalPoint_format: "."
thousandsSep_format: ","

# Mosdepoth
exclude_contigs:
  - "*_alt"
  - "*_decoy"
  - "*_random"
  - "chrUn*"
  - "HLA*"
  - "chrM"
  - "MT"
  - "chrEBV"

mosdepth_config:
  show_excluded_debug_logs: true

module_order:
  - picard
  - mosdepth
  - alignstats
  - verifyBAMID
  - fastqc
  - fastq_screen
  - kat
  - bamtools
  - goleft_indexcov
  - somalier
  - sentieon
  - vcftools
  - peddy
  - qualimap
  - verifyBAMID
  - kat
  - bcftools
  - samtools
  - samtools/stats
  - samtools/flagstat
  - samtools/idxstats
  - custom_data



# Specify the exact file patterns for the modules that go grepping through files...

bcftools/stats:
  fn: '.bcfstats.tsv'
  shared: true
#picard/crosscheckfingerprints:
# skip:
picard/gcbias:
  contents: GcBias
  shared: true
picard/hsmetrics:
  skip: true
picard/insertsize:
  contents: InsertSizeMetrics
  shared: true
picard/markdups:
  skip: true
picard/oxogmetrics:
  skip: true
picard/pcr_metrics:
  skip: true
#picard/quality_by_cycle:
  #  skip: true
picard/quality_score_distribution:
  contents_re: '[Qq]uality[Ss]core[Dd]istribution'
  contents: COUNT_OF_Q
  shared: true
picard/quality_yield_metrics:
  contents: QualityYieldMetrics
  shared: true
picard/rnaseqmetrics:
  skip: true
picard/rrbs_metrics:
  skip: true
picard/sam_file_validation:
  skip: true
picard/variant_calling_metrics:
  skip: true
#picard/wgs_metrics:
#  contents: CollectWgsMetrics
# # shared: true
#picard/collectilluminabasecallingmetrics:
#  skip: true
picard/collectilluminalanemetrics:
  skip: true
picard/extractilluminabarcodes:
  skip: true
picard/markilluminaadapters:
  skip: true

samtools/stats:
  fn: ".st.stats.tsv"

samtools/flagstat:
  fn: ".st.flagstat.tsv"

samtools/idxstats:
  fn: '.st.idxstat.tsv'

samtools/rmdup:
  skip: true

sentieon/alignment_metrics:
  fn: ".sent.mrkdup.alnstats.tsv"
sentieon/insertsize:
  fn: ".sent.mrkdup.insertmets.tsv"
sentieon/gcbias:
  fn: ".sent.mrkdup.gcsummary.tsv"

custom_data:
  alignstats_b:
    id: 'alignstats_b'
    section_name: 'alignstats_b'
    description: 'Alignstats data for General Stats'
    format: 'tsv'
    plot_type: 'generalstats'
    pconfig:
      - sample:
          hidden: False
      - InsertSizeMean:
          hidden: False
      - InsertSizeMedian:
          hidden: False
      - InsertSizeMode:
          hidden: False
      - InsertSizeStandardDeviation:
          hidden: True
      - DuplicateReadsPct:
          hidden: True
      - ChimericReadPairPct:
          hidden: True

    giabhcr_concordance:
      id: 'giabhcr_concordance'
      section_name: 'giabhcr_concordance'
      description: 'Concordance Stats For The GIAB HC Regions For This Sample'
      file_format: 'tsv'
      plot_type: 'table'
      pconfig:
        id: 'giabhcr_concordance'

sp:
  alignstats_b:
    fn: "alignstats_bsummary.tsv"
  giabhcr_concordance:
    fn: "giabhcr_concordance_mqc.tsv"


verifybamid:
  table_columns_visible:
    VerifyBAMID: true


table_cond_formatting_rules:
  mqc-generalstats-uniquely_mapped_percent:
    pass:
      - lt: 4
    warn:
      - eq: 5
    fail:
      - gt: 5


picard_config:
  insertsize_smooth_points: 5

samtools_idxstats_fraction_cutoff: 0.00001

table_columns_placement:
  somename_here_okok:
    DeletedBases: 19

  mosdepth:
    median_coverage: 10
    0_x_pc: 1
    5_x_pc: 5
    10_x_pc: 10
    15_x_pc: 15
    20_x_pc: 20
    25_x_pc: 25
    35_x_pc: 30
    40_x_pc: 40

  alignstats_b:
    InsertSizeMean: 2
    InsertSizeMedian: 3
    InsertSizeMode: 4
  custom_content:
    alignstats_b:
      InsertSizeMean: 2
      InsertSizeMedian: 3
      InsertSizeMode: 4
  custom_data:
    alignstats_b:
      InsertSizeMean: 2
      InsertSizeMedian: 3
      InsertSizeMode: 4

  Picard:
    summed_median: 5
    summed_mean: 6
    mean_coverage: 9


  VerifyBAMID:
    FREEMIX: 30

  Samtools:
    flagstat_total: 20
    reads_mapped: 1223
    properly_paired: 1222
    reads_mapped_percent: 23
    error_rate: 1020


table_columns_visible:
  somename_here_okok: true

  alignstats_b:
    InsertSizeMean: true
    InsertSizeMedian: true
    InsertSizeMode: true
  custom_content:
    alignstats_b:
      InsertSizeMean: true
      InsertSizeMedian: true
      InsertSizeMode: true
  custom_data:
    alignstats_b:
      InsertSizeMean: true
      InsertSizeMedian: true
      InsertSizeMode: true

  mosdepth:
    median_coverage: true
    0_x_pc: true
    1_x_pc: true
    2_x_pc: true
    3_x_pc: true
    4_x_pc: true
    5_x_pc: true
    6_x_pc: true

  Picard:
    mean_coverage: true
    summed_median: true
    summed_mean: true

  VerifyBAMID:
    FREEMIX: true


  FastQC: false

  qualimap: true

  Samtools:
    flagstat_total: false
    reads_mapped: false
    properly_paired: true
    reads_mapped_percent: true
    error_rate: true
