---

$schema: "http://json-schema.org/draft-04/schema#"

description: snakemake configuration file

type: object

properties:
  samples:
    type: string
  supporting_files:
    type: object
    properties:
      mode:
        type: string
      supporting_dirs:
        type: string
      webdav_point:
        type: string
      link_root:
        type: string
      link_point:
        type: string
      link_source:
        type: string
      files:
        type: object
        huref:
          type: object
          ref:
            type: string
          rtg_tools_genome:
            type: string
          truth_data:
            type: string
          calling_regions:
            type: string
        contam:
          type: object
          ref_vcf:
            type: string
          readthrough_reportable_range_fp:
            type: string
          readthrough_reportable_range_mendeliome_fp:
            type: string
        iddnas:
          type: object
          iddnas_barcodes_fp:
            type: string
        fastv:
          type: object
          js_files:
            type: string
          kmer_collection:
            type: string
          kmer:
            type: string
          genomes:
            type: string
        octopus:
          type: object
          forest_model:
            type: string
          error_model:
            type: string
          skip_regions_f:
            type: string
      required:
      - files

required:
    - samples
