---
supporting_files:   ## All of this structure was for an exploratory, now deprecated , system that let you declare resources from mixed sources.  It's simply paths now :-)  And if not leading with a '/', then is relative to the snakemake working dir.
  root: /fsx/data/
  files:
    huref:
      genome_file:
        name: createme
      bed:
        name: /fsx/data/genomic_data/organism_references/H_sapiens/hg38_broad/hg38_broad.bed
      female_diploid:
        name: /fsx/data/genomic_data/organism_references/H_sapiens/hg38_broad/hg38_diploid_female.bed
      female_haploid:
        name: ""
      male_diploid:
        name: /fsx/data/genomic_data/organism_references/H_sapiens/hg38_broad/hg38_diploid_male.bed
      male_haploid:
        name: /fsx/data/genomic_data/organism_references/H_sapiens/hg38_broad/hg38_haploid_male.bed
      core_bed:
        name: /fsx/data/genomic_data/organism_references/H_sapiens/hg38_broad/hg38_broad_core.bed
      fasta:
        name: /fsx/data/genomic_data/organism_references/H_sapiens/hg38_broad/Homo_sapiens_assembly38.fasta
        bed: /fsx/data/genomic_data/organism_references/H_sapiens/hg38_broad/hg38_broad_core.bed
        namenogz: /fsx/data/genomic_data/organism_references/H_sapiens/hg38/broad_hg38/Homo_sapiens_assembly38.fasta
      hisat2:
        name: /fsx/data/genomic_data/organism_references/H_sapiens/hg38/blah.createme.note
      rtg_tools_genome_full:
        name: /fsx/data/genomic_data/organism_references/H_sapiens/hg38_broad/rtg/Homo_sapiens_assembly38.fasta.sdf
      rtg_tools_genome_noalt:
        name: /fsx/data/genomic_data/organism_references/H_sapiens/hg38/fasta_fai_minalt/GRCh38_no_alt_analysis_set.fasta.sdf
      rtg_tools_genome:
        name: /fsx/data/genomic_data/organism_references/H_sapiens/hg38/fasta_fai_minalt/GRCh38_no_alt_analysis_set.fasta.sdf
    vep:
      vep_genome_build: 113_GRCh38
      vep_cache:
        name: /fsx/data/tool_specific_data/vep/
    snpeff:
      ref_build_code: GRCh38.99
    ucsc:
      simple_repeats_bed:
        name: /fsx/data/genomic_data/organism_annotations/H_sapiens/hg38/ucsc/ucsc_hg38_simple_repeats.bed
      dbsnp152:
        name: /fsx/data/genomic_data/organism_annotations/H_sapiens/hg38/ncbi/dbsnp/GCF_000001405.40.vcf.gz.tbi/GCF_000001405.40.vcf.gz
      build_gaps:
        name: resources/grch38_ucsc_gaps.bed 
    dbsnp:
      broad_snowman_indelvcf:
        name: /fsx/data/genomic_data/organism_annotations/H_sapiens/hg38/ncbi/dbsnp/GCF_000001405.40.vcf.gz.tbi/GCF_000001405.40.vcf.gz
    iddnas:
      human_iddnas:
        name: createme
      alien_iddnas:
        name: createme
      both_human_alien:
        name: createme
    verifybam2:
      dat_files:
        name: /fsx/data/genomic_data/organism_annotations/H_sapiens/hg38/snp_vcfs/snp_subset_1M/filtered_vcfs/merged.500perchr.nosamp.sort.vcf.gz 
      oneM_snps_vcf:
        name: /fsx/data/genomic_data/organism_annotations/H_sapiens/hg38/snp_vcfs/snp_subset_1M/filtered_vcfs/merged.500perchr.nosamp.sort.vcf.gz
      oneM_snps_bed:
        name: /fsx/data/genomic_data/organism_annotations/H_sapiens/hg38/snp_vcfs/snp_subset_1M/filtered_vcfs/merged.500perchr.nosamp.sort.vcf.gz
    fastv:
      microbial_kmer_collection:
        name: createme
      influenza_kmer_collection:
        name: createme
      covid_kmer:
        name: createme
      covid_genomes:
        name: createme
    glimpse:
      GLIMPSE_huref:
        name: createme
      GLIMPSE_noNA12878_sites:
        name: createme
    somalier:
      genome_sites:
        name: createme
    octopus:
      forest_model_a:
        name: /fsx/data/tool_specific_resources/H_sapiens/b37/octopus/forests/germline.v0.7.4.forest
    microbial:
      reprDB:  # https://pubmed.ncbi.nlm.nih.gov/29347966/
        name: createme
      panDB:
        name: createme
        # https://microbiomejournal.biomedcentral.com/articles/10.1186/s40168-018-0399-2
        # https://github.com/ohlab/panDB
    giab_sv:
      v0.6_NA24385_ties_1_2:
        name: /fsx/data/genomic_data/organism_annotations/H_sapiens/hg38/controls/giab/snv/v4.2.1/HG001/giabHC/HG001.bed

 
