---
log: logs/supporting_dirs.log

root:
  a: fsx/locus
  b: fsx/data/
  c: fsx/data/
  d: fsx/data/
  e: fsx/data/
  f: fsx/data/genomic_data/
  g: fsx/data/genomic_data/organism_refrences/
  h: fsx/data/genomic_data/organism_refrences/human/
  i: fsx/data/genomic_data/organism_refrences/human_g1k_v37/
  j: fsx/data/genomic_data/organism_refrences/human_g1k_v37/human_g1k_v37_sdf/
  k: fsx/data/genomic_data/organism_refrences/human_g1k_v37/bwa-mem2/
  l: fsx/data/genomic_data/organism_refrences/human_g1k_v37/bwa-mem2vanilla/
  ll: fsx/data/genomic_data/organism_refrences/human_g1k_v37/bwa_meme/
  m: fsx/data/genomic_data/organism_refrences/controls/
  n: fsx/data/genomic_data/organism_refrences/controls/b37/
  o: fsx/data/genomic_data/organism_refrences/controls/b37/controls/
  p: fsx/data/tool_specific_fsx/fastv/
  q: fsx/data/tool_specific_fsx/fastv/data/
  r: fsx/data/tool_specific_fsx/octopus/
  s: fsx/data/tool_specific_fsx/octopus/octopus_err_models/
  t: fsx/data/tool_specific_fsx/octopus/forests/
