alignmentExome.bait_intervals: gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes_bait.interval_list

alignmentExome.target_intervals: gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes_target.interval_list

alignmentExome.sequence:
- sequence:
    bam: gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/unaligned_subset_bams/tumor/2895499223.bam
  readgroup: "@RG\tID:2895499223\tPU:H7HY2CCXX.3\tSM:H_NJ-HCC1395-HCC1395\tLB:H_NJ-HCC1395-HCC1395-lg24-lib1\tPL:ILLUMINA\tCN:WUGSC"
- sequence:
    bam: gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/unaligned_subset_bams/tumor/2895499237.bam
  readgroup: "@RG\tID:2895499237\tPU:H7HY2CCXX.4\tSM:H_NJ-HCC1395-HCC1395\tLB:H_NJ-HCC1395-HCC1395-lg24-lib1\tPL:ILLUMINA\tCN:WUGSC"

alignmentExome.omni_vcf: gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes_omni.vcf.gz
alignmentExome.omni_vcf_tbi: gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes_omni.vcf.gz.tbi

alignmentExome.bqsr_known_sites:
- gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes_omni.vcf.gz
- gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes_dbsnp.vcf.gz
- gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes_mills.vcf.gz
- gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes_known_indels.vcf.gz

alignmentExome.bqsr_known_sites_tbi:
- gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes_omni.vcf.gz.tbi
- gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes_dbsnp.vcf.gz.tbi
- gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes_mills.vcf.gz.tbi
- gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes_known_indels.vcf.gz.tbi

alignmentExome.picard_metric_accumulation_level: LIBRARY

alignmentExome.reference: gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes.fa
alignmentExome.reference_fai: gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes.fa.fai
alignmentExome.reference_dict: gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes.dict
alignmentExome.reference_alt: gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes.fa.alt
alignmentExome.reference_amb: gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes.fa.amb
alignmentExome.reference_ann: gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes.fa.ann
alignmentExome.reference_bwt: gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes.fa.bwt
alignmentExome.reference_pac: gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes.fa.pac
alignmentExome.reference_sa: gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes.fa.sa

alignmentExome.bqsr_intervals:
- chr6
- chr17

alignmentExome.per_base_intervals:
- file: gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes_target.interval_list
  label: clinvar

alignmentExome.per_target_intervals:
- file: gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes_target.interval_list
  label: acmg_genes

alignmentExome.summary_intervals: []

alignmentExome.final_name: H_NJ-HCC1395-HCC1395
