detectVariants.reference: gs://griffith-lab-cromwell/input_data/maruska/2021-04-26/somatic_inputs/hla_and_brca_genes.fa
detectVariants.reference_fai: gs://griffith-lab-cromwell/input_data/maruska/2021-04-26/somatic_inputs/hla_and_brca_genes.fa.fai
detectVariants.reference_dict: gs://griffith-lab-cromwell/input_data/maruska/2021-04-26/somatic_inputs/hla_and_brca_genes.dict

# --- Normal ---

detectVariants.normal_sample_name: H_NJ-HCC1395-HCC1395_BL

detectVariants.normal_bam: gs://griffith-lab-cromwell/cromwell-executions/alignmentExome/0c0a333a-c314-4d01-b6cd-96c8a586a7f5/call-alignment/sequenceToBqsr/43a942b1-163b-4dbe-91e8-0e047c6c6db2/call-applyBqsr/H_NJ-HCC1395-HCC1395_BL.bam
detectVariants.normal_bam_bai: gs://griffith-lab-cromwell/cromwell-executions/alignmentExome/0c0a333a-c314-4d01-b6cd-96c8a586a7f5/call-alignment/sequenceToBqsr/43a942b1-163b-4dbe-91e8-0e047c6c6db2/call-indexBam/H_NJ-HCC1395-HCC1395_BL.bam.bai

# --- Tumor ---

detectVariants.tumor_sample_name: H_NJ-HCC1395-HCC1395

detectVariants.tumor_bam: gs://griffith-lab-cromwell/cromwell-executions/alignmentExome/1b955790-a3c1-4cf2-8371-bf415f3525a1/call-alignment/sequenceToBqsr/c6ccbfef-2a84-4f50-be00-396017d1be0c/call-applyBqsr/H_NJ-HCC1395-HCC1395.bam
detectVariants.tumor_bam_bai: gs://griffith-lab-cromwell/cromwell-executions/alignmentExome/1b955790-a3c1-4cf2-8371-bf415f3525a1/call-alignment/sequenceToBqsr/c6ccbfef-2a84-4f50-be00-396017d1be0c/call-indexBam/H_NJ-HCC1395-HCC1395.bam.bai

# -------------

detectVariants.roi_intervals: gs://griffith-lab-cromwell/cromwell-executions/wf/e985ed7a-80fd-45aa-ae9a-2e20468de5f3/call-intervalListExpand/hla_and_brca_genes_target.expanded.interval_list
detectVariants.scatter_count: 50

detectVariants.strelka_cpu_reserved: 8
detectVariants.strelka_exome_mode: true

detectVariants.varscan_min_coverage: 8
detectVariants.varscan_min_var_freq: 0.05
detectVariants.varscan_p_value: 0.99

detectVariants.pindel_insert_size: 400

detectVariants.filter_docm_variants: true

detectVariants.cle_vcf_filter: false

detectVariants.vep_cache_dir_zip: gs://griffith-lab-cromwell/input_data/vep.zip
detectVariants.vep_custom_annotations: []
# vep_custom_annotations:
# - annotation:
#     check_existing: 'true'
#     data_format: vcf
#     file: gs://griffith-lab-cromwell/input_data/maruska/2021-04-15/gc2560/core/model_data/genome-db-ensembl-gnomad/2dd4b53431674786b760adad60a29273/fixed_b38_exome.vcf.gz
#       secondaryFiles:
#       - gs://griffith-lab-cromwell/input_data/maruska/2021-04-15/gc2560/core/model_data/genome-db-ensembl-gnomad/2dd4b53431674786b760adad60a29273/fixed_b38_exome.vcf.gz.tbi
#     gnomad_filter: 'true'
#     name: gnomADe
#     vcf_fields:
#     - AF
#     - AF_AFR
#     - AF_AMR
#     - AF_ASJ
#     - AF_EAS
#     - AF_FIN
#     - AF_NFE
#     - AF_OTH
#     - AF_SAS
#   force_report_coordinates: 'true'
#   method: exact
# - annotation:
#     check_existing: 'false'
#     data_format: vcf
#     file:
#       class: File
#       path: gs://griffith-lab-cromwell/input_data/maruska/2021-04-15/gc2560/core/custom_clinvar_vcf/v20181028/custom.vcf.gz
#       secondaryFiles:
#       - class: File
#         path: gs://griffith-lab-cromwell/input_data/maruska/2021-04-15/gc2560/core/custom_clinvar_vcf/v20181028/custom.vcf.gz.tbi
#     gnomad_filter: 'false'
#     name: clinvar
#     vcf_fields:
#     - CLINSIGN
#     - PHENOTYPE
#     - SCORE
#     - RCVACC
#     - TESTEDINGTR
#     - PHENOTYPELIST
#     - NUMSUBMIT
#     - GUIDELINES
#   force_report_coordinates: 'true'
#   method: exact

detectVariants.vep_ensembl_assembly: GRCh38
detectVariants.vep_ensembl_species: homo_sapiens
detectVariants.vep_ensembl_version: '95'
detectVariants.vep_to_table_fields:
  - Consequence
  - SYMBOL
  - Feature_type
  - Feature
  - HGVSc
  - HGVSp
  - cDNA_position
  - CDS_position
  - Protein_position
  - Amino_acids
  - Codons
  - HGNC_ID
  - Existing_variation
  - gnomADe_AF
  - CLIN_SIG
  - SOMATIC
  - PHENO
  - clinvar_CLINSIGN
  - clinvar_PHENOTYPE
  - clinvar_SCORE
  - clinvar_RCVACC
  - clinvar_TESTEDINGTR
  - clinvar_PHENOTYPELIST
  - clinvar_NUMSUBMIT
  - clinvar_GUIDELINES

detectVariants.synonyms_file: gs://griffith-lab-cromwell/input_data/maruska/2021-04-15/gc2560/core/model_data/2887491634/build50f99e75d14340ffb5b7d21b03887637/chromAlias.ensembl.txt

detectVariants.filter_somatic_llr_threshold: 5
detectVariants.filter_somatic_llr_tumor_purity: 1
detectVariants.filter_somatic_llr_normal_contamination_rate: 0

detectVariants.cle_vcf_filter: false

detectVariants.filter_somatic_llr_normal_contamination_rate: 0
detectVariants.filter_somatic_llr_threshold: 5
detectVariants.filter_somatic_llr_tumor_purity: 1

detectVariants.variants_to_table_fields:
  - CHROM
  - POS
  - REF
  - ALT
  - set
  - AC
  - AF

detectVariants.variants_to_table_genotype_fields:
  - GT
  - AD

detectVariants.docm_vcf: gs://griffith-lab-cromwell/input_data/maruska/2021-04-26/somatic_inputs/hla_and_brca_genes_docm.vcf.gz
detectVariants.docm_vcf_tbi: gs://griffith-lab-cromwell/input_data/maruska/2021-04-26/somatic_inputs/hla_and_brca_genes_docm.vcf.gz.tbi
