---
immuno.reference: gs://griffith-lab-cromwell/input_data/maruska/2021-10-11/somatic_inputs/hla_and_brca_genes.fa
immuno.reference_fai: gs://griffith-lab-cromwell/input_data/maruska/2021-10-11/somatic_inputs/hla_and_brca_genes.fa.fai
immuno.reference_dict: gs://griffith-lab-cromwell/input_data/maruska/2021-10-11/somatic_inputs/hla_and_brca_genes.dict
immuno.reference_alt: gs://griffith-lab-cromwell/input_data/maruska/2021-10-11/somatic_inputs/hla_and_brca_genes.fa.alt
immuno.reference_amb: gs://griffith-lab-cromwell/input_data/maruska/2021-10-11/somatic_inputs/hla_and_brca_genes.fa.amb
immuno.reference_ann: gs://griffith-lab-cromwell/input_data/maruska/2021-10-11/somatic_inputs/hla_and_brca_genes.fa.ann
immuno.reference_bwt: gs://griffith-lab-cromwell/input_data/maruska/2021-10-11/somatic_inputs/hla_and_brca_genes.fa.bwt
immuno.reference_pac: gs://griffith-lab-cromwell/input_data/maruska/2021-10-11/somatic_inputs/hla_and_brca_genes.fa.pac
immuno.reference_sa: gs://griffith-lab-cromwell/input_data/maruska/2021-10-11/somatic_inputs/hla_and_brca_genes.fa.sa

immuno.tumor_sample_name: 'H_NJ-HCC1395-HCC1395'
immuno.normal_sample_name: 'H_NJ-HCC1395-HCC1395_BL'

# ---------- RNAseq Inputs ---------------------------------------------

immuno.gene_transcript_lookup_table: gs://griffith-lab-cromwell/input_data/maruska/2021-10-11/rna_inputs/subset_transcriptToGene.tsv

# JEM These are missing in my example data
immuno.rna_sequence:
  - sequence:
      bam: gs://griffith-lab-cromwell/input_data/maruska/2021-10-11/unaligned_subset_bams/rna/2895626107.bam
  - sequence:
      bam: gs://griffith-lab-cromwell/input_data/maruska/2021-10-11/unaligned_subset_bams/rna/2895626112.bam

immuno.kallisto_index: gs://griffith-lab-cromwell/input_data/maruska/2021-10-11/rna_inputs/subset_transcripts_kallisto.idx

immuno.read_group_fields:
- - PU:H3MYFBBXX.4
  - SM:H_NJ-HCC1395-HCC1395_RNA
  - LB:Pooled_RNA_2891007020-cD1-lib1
  - PL:Illumina
  - CN:WUGSC
- - PU:H3MYFBBXX.5
  - SM:H_NJ-HCC1395-HCC1395_RNA
  - LB:Pooled_RNA_2891007020-cD1-lib1
  - PL:Illumina
  - CN:WUGSC

immuno.rna_readgroups:
- "2895626107"
- "2895626112"

immuno.refFlat: gs://griffith-lab-cromwell/input_data/maruska/2021-10-11/rna_inputs/subset_refFlat.txt

immuno.reference_annotation: gs://griffith-lab-cromwell/input_data/maruska/2021-10-11/rna_inputs/subset_annotation.gtf

immuno.reference_index: gs://griffith-lab-cromwell/input_data/maruska/2021-10-11/rna_inputs/hisat/subset_hisat_index
immuno.reference_index_1ht2: gs://griffith-lab-cromwell/input_data/maruska/2021-10-11/rna_inputs/hisat/subset_hisat_index.1.ht2
immuno.reference_index_2ht2: gs://griffith-lab-cromwell/input_data/maruska/2021-10-11/rna_inputs/hisat/subset_hisat_index.2.ht2
immuno.reference_index_3ht2: gs://griffith-lab-cromwell/input_data/maruska/2021-10-11/rna_inputs/hisat/subset_hisat_index.3.ht2
immuno.reference_index_4ht2: gs://griffith-lab-cromwell/input_data/maruska/2021-10-11/rna_inputs/hisat/subset_hisat_index.4.ht2
immuno.reference_index_5ht2: gs://griffith-lab-cromwell/input_data/maruska/2021-10-11/rna_inputs/hisat/subset_hisat_index.5.ht2
immuno.reference_index_6ht2: gs://griffith-lab-cromwell/input_data/maruska/2021-10-11/rna_inputs/hisat/subset_hisat_index.6.ht2
immuno.reference_index_7ht2: gs://griffith-lab-cromwell/input_data/maruska/2021-10-11/rna_inputs/hisat/subset_hisat_index.7.ht2
immuno.reference_index_8ht2: gs://griffith-lab-cromwell/input_data/maruska/2021-10-11/rna_inputs/hisat/subset_hisat_index.8.ht2

immuno.sample_name: H_NJ-HCC1395-HCC1395_RNA

immuno.strand: first

immuno.trimming_adapter_min_overlap: 7

immuno.trimming_adapter_trim_end: RIGHT

immuno.trimming_adapters: gs://griffith-lab-cromwell/input_data/maruska/2021-10-11/rna_inputs/illumina_multiplex.fa

immuno.trimming_max_uncalled: 300

immuno.trimming_min_readlength: 25


# --------- Somatic Inputs ---------------------------------------------

immuno.vep_ensembl_species: homo_sapiens
immuno.vep_ensembl_assembly: GRCh38

immuno.bait_intervals: gs://griffith-lab-cromwell/input_data/maruska/2021-10-11/somatic_inputs/hla_and_brca_genes_bait.interval_list

immuno.target_intervals: gs://griffith-lab-cromwell/input_data/maruska/2021-10-11/somatic_inputs/hla_and_brca_genes_target.interval_list

immuno.normal_sequence:
  - sequence:
      bam: gs://griffith-lab-cromwell/input_data/maruska/2021-10-11/unaligned_subset_bams/normal/2895499331.bam
    readgroup: "@RG\tID:2895499331\tPU:H7HY2CCXX.3\tSM:H_NJ-HCC1395-HCC1395_BL\tLB:H_NJ-HCC1395-HCC1395_BL-lg21-lib1\tPL:Illumina\tCN:WUGSC"
  - sequence:
      bam: gs://griffith-lab-cromwell/input_data/maruska/2021-10-11/unaligned_subset_bams/normal/2895499399.bam
    readgroup: "@RG\tID:2895499399\tPU:H7HY2CCXX.4\tSM:H_NJ-HCC1395-HCC1395_BL\tLB:H_NJ-HCC1395-HCC1395_BL-lg21-lib1\tPL:Illumina\tCN:WUGSC"

immuno.tumor_sequence:
  - sequence:
      bam: gs://griffith-lab-cromwell/input_data/maruska/2021-10-11/unaligned_subset_bams/tumor/2895499223.bam
    readgroup: "@RG\tID:2895499223\tPU:H7HY2CCXX.3\tSM:H_NJ-HCC1395-HCC1395\tLB:H_NJ-HCC1395-HCC1395-lg24-lib1\tPL:ILLUMINA\tCN:WUGSC"
  - sequence:
      bam: gs://griffith-lab-cromwell/input_data/maruska/2021-10-11/unaligned_subset_bams/tumor/2895499237.bam
    readgroup: "@RG\tID:2895499237\tPU:H7HY2CCXX.4\tSM:H_NJ-HCC1395-HCC1395\tLB:H_NJ-HCC1395-HCC1395-lg24-lib1\tPL:ILLUMINA\tCN:WUGSC"

immuno.docm_vcf: gs://griffith-lab-cromwell/input_data/maruska/2021-04-26/somatic_inputs/hla_and_brca_genes_docm.vcf.gz
immuno.docm_vcf_tbi: gs://griffith-lab-cromwell/input_data/maruska/2021-04-26/somatic_inputs/hla_and_brca_genes_docm.vcf.gz.tbi

immuno.omni_vcf: gs://griffith-lab-cromwell/input_data/maruska/2021-10-11/somatic_inputs/hla_and_brca_genes_omni.vcf.gz
immuno.omni_vcf_tbi: gs://griffith-lab-cromwell/input_data/maruska/2021-10-11/somatic_inputs/hla_and_brca_genes_omni.vcf.gz.tbi


immuno.bqsr_known_sites:
  - gs://griffith-lab-cromwell/input_data/maruska/2021-10-11/somatic_inputs/hla_and_brca_genes_omni.vcf.gz
  - gs://griffith-lab-cromwell/input_data/maruska/2021-10-11/somatic_inputs/hla_and_brca_genes_dbsnp.vcf.gz
  - gs://griffith-lab-cromwell/input_data/maruska/2021-10-11/somatic_inputs/hla_and_brca_genes_mills.vcf.gz
  - gs://griffith-lab-cromwell/input_data/maruska/2021-10-11/somatic_inputs/hla_and_brca_genes_known_indels.vcf.gz

immuno.bqsr_known_sites_tbi:
  - gs://griffith-lab-cromwell/input_data/maruska/2021-10-11/somatic_inputs/hla_and_brca_genes_omni.vcf.gz.tbi
  - gs://griffith-lab-cromwell/input_data/maruska/2021-10-11/somatic_inputs/hla_and_brca_genes_dbsnp.vcf.gz.tbi
  - gs://griffith-lab-cromwell/input_data/maruska/2021-10-11/somatic_inputs/hla_and_brca_genes_mills.vcf.gz.tbi
  - gs://griffith-lab-cromwell/input_data/maruska/2021-10-11/somatic_inputs/hla_and_brca_genes_known_indels.vcf.gz.tbi

immuno.picard_metric_accumulation_level: LIBRARY

immuno.somalier_vcf: gs://griffith-lab-cromwell/input_data/maruska/2021-10-11/somatic_inputs/subset_somalier.vcf

immuno.synonyms_file: gs://griffith-lab-cromwell/input_data/maruska/2021-04-15/gc2560/core/model_data/2887491634/build50f99e75d14340ffb5b7d21b03887637/chromAlias.ensembl.txt

immuno.vep_cache_dir_zip: gs://griffith-lab-cromwell/input_data/vep.zip

immuno.vep_ensembl_version: '95'

immuno.scatter_count: 2

immuno.vep_to_table_fields:
- Consequence
- SYMBOL
- Feature_type
- Feature
- HGVSc
- HGVSp
- cDNA_position
- CDS_position
- Protein_position
- Amino_acids
- Codons
- HGNC_ID
- Existing_variation
- gnomADe_AF
- CLIN_SIG
- SOMATIC
- PHENO

immuno.bqsr_intervals:
- chr6
- chr17

immuno.variants_to_table_fields:
- CHROM
- POS
- REF
- ALT
- set

immuno.variants_to_table_genotype_fields:
- GT
- AD
- AF
- DP

immuno.per_base_intervals:
- file: gs://griffith-lab-cromwell/input_data/maruska/2021-10-11/somatic_inputs/hla_and_brca_genes_target.interval_list
  label: clinvar

immuno.per_target_intervals:
- file: gs://griffith-lab-cromwell/input_data/maruska/2021-10-11/somatic_inputs/hla_and_brca_genes_target.interval_list
  label: acmg_genes

immuno.summary_intervals: []

immuno.vep_custom_annotations: []

# ---------- Germline Inputs -------------------------------------------

immuno.gvcf_gq_bands: []

immuno.gatk_haplotypecaller_intervals:
- - chr6
- - chr17

# ---------- PVACseq Inputs --------------------------------------------

immuno.prediction_algorithms:
- NetMHC
