rnaseq.reference: gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes.fa
rnaseq.reference_fai: gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes.fa.fai
rnaseq.reference_dict: gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes.dict

rnaseq.gene_transcript_lookup_table: gs://griffith-lab-cromwell/input_data/maruska/2021-07-30/rna_inputs/subset_transcriptToGene.tsv

rnaseq.instrument_data_bams:
- gs://griffith-lab-cromwell/input_data/maruska/2021-07-30/unaligned_subset_bams/rna/2895626107.bam
- gs://griffith-lab-cromwell/input_data/maruska/2021-07-30/unaligned_subset_bams/rna/2895626112.bam

rnaseq.kallisto_index: gs://griffith-lab-cromwell/input_data/maruska/2021-07-30/rna_inputs/subset_transcripts_kallisto.idx

rnaseq.read_group_fields:
- - PU:H3MYFBBXX.4
  - SM:H_NJ-HCC1395-HCC1395_RNA
  - LB:Pooled_RNA_2891007020-cD1-lib1
  - PL:Illumina
  - CN:WUGSC
- - PU:H3MYFBBXX.5
  - SM:H_NJ-HCC1395-HCC1395_RNA
  - LB:Pooled_RNA_2891007020-cD1-lib1
  - PL:Illumina
  - CN:WUGSC

rnaseq.read_group_id:
- "2895626107"
- "2895626112"

rnaseq.refFlat: gs://griffith-lab-cromwell/input_data/maruska/2021-07-30/rna_inputs/subset_refFlat.txt

rnaseq.reference_annotation: gs://griffith-lab-cromwell/input_data/maruska/2021-07-30/rna_inputs/subset_annotation.gtf

rnaseq.reference_index: gs://griffith-lab-cromwell/input_data/maruska/2021-07-30/rna_inputs/hisat/subset_hisat_index
rnaseq.reference_index_1ht2: gs://griffith-lab-cromwell/input_data/maruska/2021-07-30/rna_inputs/hisat/subset_hisat_index.1.ht2
rnaseq.reference_index_2ht2: gs://griffith-lab-cromwell/input_data/maruska/2021-07-30/rna_inputs/hisat/subset_hisat_index.2.ht2
rnaseq.reference_index_3ht2: gs://griffith-lab-cromwell/input_data/maruska/2021-07-30/rna_inputs/hisat/subset_hisat_index.3.ht2
rnaseq.reference_index_4ht2: gs://griffith-lab-cromwell/input_data/maruska/2021-07-30/rna_inputs/hisat/subset_hisat_index.4.ht2
rnaseq.reference_index_5ht2: gs://griffith-lab-cromwell/input_data/maruska/2021-07-30/rna_inputs/hisat/subset_hisat_index.5.ht2
rnaseq.reference_index_6ht2: gs://griffith-lab-cromwell/input_data/maruska/2021-07-30/rna_inputs/hisat/subset_hisat_index.6.ht2
rnaseq.reference_index_7ht2: gs://griffith-lab-cromwell/input_data/maruska/2021-07-30/rna_inputs/hisat/subset_hisat_index.7.ht2
rnaseq.reference_index_8ht2: gs://griffith-lab-cromwell/input_data/maruska/2021-07-30/rna_inputs/hisat/subset_hisat_index.8.ht2

rnaseq.sample_name: H_NJ-HCC1395-HCC1395_RNA

rnaseq.strand: first

rnaseq.trimming_adapter_min_overlap: 7

rnaseq.trimming_adapter_trim_end: RIGHT

rnaseq.trimming_adapters: gs://griffith-lab-cromwell/input_data/maruska/2021-07-30/rna_inputs/illumina_multiplex.fa

rnaseq.trimming_max_uncalled: 300

rnaseq.trimming_min_readlength: 25
