rnaseqStarFusion.reference: gs://griffith-lab-cromwell/input_data/GRC-human-build38_human_95_38_U2AF1_fix/rna_seq_annotation/all_sequences.fa
rnaseqStarFusion.reference_fai: gs://griffith-lab-cromwell/input_data/GRC-human-build38_human_95_38_U2AF1_fix/rna_seq_annotation/all_sequences.fa.fai
rnaseqStarFusion.reference_dict: gs://griffith-lab-cromwell/input_data/GRC-human-build38_human_95_38_U2AF1_fix/rna_seq_annotation/all_sequences.dict

rnaseqStarFusion.unaligned:
    - sequence:
        fastq1: gs://griffith-lab-cromwell/cromwell-executions/wf/a4880a2d-5f07-45e1-8bdf-ffaa04e9232d/call-bamToFastq/shard-0/read1.fastq
        fastq2: gs://griffith-lab-cromwell/cromwell-executions/wf/a4880a2d-5f07-45e1-8bdf-ffaa04e9232d/call-bamToFastq/shard-0/read2.fastq
    - sequence:
        fastq1: gs://griffith-lab-cromwell/cromwell-executions/wf/a4880a2d-5f07-45e1-8bdf-ffaa04e9232d/call-bamToFastq/shard-1/read1.fastq
        fastq2: gs://griffith-lab-cromwell/cromwell-executions/wf/a4880a2d-5f07-45e1-8bdf-ffaa04e9232d/call-bamToFastq/shard-1/read2.fastq
rnaseqStarFusion.sample_name: H_NJ-HCC1395-HCC1395_RNA
rnaseqStarFusion.strand: second

rnaseqStarFusion.outsam_attrrg_line:
  - "ID:2895626107 PU:H3MYFBBXX5.4.GCCAAT SM:H_NJ-HCC1395-HCC1395_RNA LB:Pooled_RNA_2891007020-cD1-lib1 PL:Illumina CN:WUGSC"
  - "ID:2895626112 PU:H3MYFBBXX5.5.GCCAAT SM:H_NJ-HCC1395-HCC1395_RNA LB:Pooled_RNA_2891007020-cD1-lib1 PL:Illumina CN:WUGSC"

rnaseqStarFusion.star_genome_dir_zip: gs://griffith-lab-cromwell/input_data/GRC-human-build38_human_95_38_U2AF1_fix/rna_seq_annotation/star_2.7.0f_index.zip
rnaseqStarFusion.star_fusion_genome_dir_zip: gs://griffith-lab-cromwell/input_data/GRC-human-build38_human_95_38_U2AF1_fix/rna_seq_annotation/star_fusion_1.8.0_index.zip
rnaseqStarFusion.cdna_fasta: gs://griffith-lab-cromwell/input_data/GRC-human-build38_human_95_38_U2AF1_fix/rna_seq_annotation/Homo_sapiens.GRCh38.cdna.all.fa.gz
rnaseqStarFusion.gtf_file: gs://griffith-lab-cromwell/input_data/GRC-human-build38_human_95_38_U2AF1_fix/rna_seq_annotation/Homo_sapiens.GRCh38.95.gtf

rnaseqStarFusion.trimming_adapter_min_overlap: 7
rnaseqStarFusion.trimming_adapter_trim_end: RIGHT
rnaseqStarFusion.trimming_adapters: gs://griffith-lab-cromwell/input_data/maruska/2021-10-11/rna_inputs/illumina_multiplex.fa
rnaseqStarFusion.trimming_max_uncalled: 300
rnaseqStarFusion.trimming_min_readlength: 25

rnaseqStarFusion.kallisto_index: gs://griffith-lab-cromwell/input_data/GRC-human-build38_human_95_38_U2AF1_fix/rna_seq_annotation/Homo_sapiens.GRCh38.cdna.all.fa.kallisto.idx
rnaseqStarFusion.gene_transcript_lookup_table: gs://griffith-lab-cromwell/input_data/GRC-human-build38_human_95_38_U2AF1_fix/rna_seq_annotation/ensembl95.transcriptToGene.tsv
rnaseqStarFusion.refFlat: gs://griffith-lab-cromwell/input_data/GRC-human-build38_human_95_38_U2AF1_fix/rna_seq_annotation/Homo_sapiens.GRCh38.95.refFlat.txt
rnaseqStarFusion.ribosomal_intervals: gs://griffith-lab-cromwell/input_data/GRC-human-build38_human_95_38_U2AF1_fix/rna_seq_annotation/Homo_sapiens.GRCh38.95.ribo_intervals
