---
somaticExome.vep_ensembl_species: homo_sapiens

somaticExome.vep_ensembl_assembly: GRCh38

somaticExome.bait_intervals: gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes_bait.interval_list

somaticExome.target_intervals: gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes_target.interval_list

somaticExome.normal_sequence:
  - sequence:
      bam: gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/unaligned_subset_bams/normal/2895499331.bam
    readgroup: "@RG\tID:2895499331\tPU:H7HY2CCXX.3\tSM:H_NJ-HCC1395-HCC1395_BL\tLB:H_NJ-HCC1395-HCC1395_BL-lg21-lib1\tPL:Illumina\tCN:WUGSC"
  - sequence:
      bam: gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/unaligned_subset_bams/normal/2895499399.bam
    readgroup: "@RG\tID:2895499399\tPU:H7HY2CCXX.4\tSM:H_NJ-HCC1395-HCC1395_BL\tLB:H_NJ-HCC1395-HCC1395_BL-lg21-lib1\tPL:Illumina\tCN:WUGSC"

somaticExome.tumor_sequence:
  - sequence:
      bam: gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/unaligned_subset_bams/tumor/2895499223.bam
    readgroup: "@RG\tID:2895499223\tPU:H7HY2CCXX.3\tSM:H_NJ-HCC1395-HCC1395\tLB:H_NJ-HCC1395-HCC1395-lg24-lib1\tPL:ILLUMINA\tCN:WUGSC"
  - sequence:
      bam: gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/unaligned_subset_bams/tumor/2895499237.bam
    readgroup: "@RG\tID:2895499237\tPU:H7HY2CCXX.4\tSM:H_NJ-HCC1395-HCC1395\tLB:H_NJ-HCC1395-HCC1395-lg24-lib1\tPL:ILLUMINA\tCN:WUGSC"

somaticExome.docm_vcf: gs://griffith-lab-cromwell/input_data/maruska/2021-04-26/somatic_inputs/hla_and_brca_genes_docm.vcf.gz
somaticExome.docm_vcf_tbi: gs://griffith-lab-cromwell/input_data/maruska/2021-04-26/somatic_inputs/hla_and_brca_genes_docm.vcf.gz.tbi

somaticExome.omni_vcf: gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes_omni.vcf.gz
somaticExome.omni_vcf_tbi: gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes_omni.vcf.gz.tbi


somaticExome.bqsr_known_sites:
  - gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes_omni.vcf.gz
  - gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes_dbsnp.vcf.gz
  - gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes_mills.vcf.gz
  - gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes_known_indels.vcf.gz

somaticExome.bqsr_known_sites_tbi:
  - gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes_omni.vcf.gz.tbi
  - gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes_dbsnp.vcf.gz.tbi
  - gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes_mills.vcf.gz.tbi
  - gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes_known_indels.vcf.gz.tbi

somaticExome.picard_metric_accumulation_level: LIBRARY

somaticExome.reference: gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes.fa
somaticExome.reference_fai: gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes.fa.fai
somaticExome.reference_dict: gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes.dict
somaticExome.reference_alt: gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes.fa.alt
somaticExome.reference_amb: gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes.fa.amb
somaticExome.reference_ann: gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes.fa.ann
somaticExome.reference_bwt: gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes.fa.bwt
somaticExome.reference_pac: gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes.fa.pac
somaticExome.reference_sa: gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes.fa.sa

somaticExome.somalier_vcf: gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/subset_somalier.vcf

somaticExome.synonyms_file: gs://griffith-lab-cromwell/input_data/maruska/2021-04-15/gc2560/core/model_data/2887491634/build50f99e75d14340ffb5b7d21b03887637/chromAlias.ensembl.txt

somaticExome.vep_cache_dir_zip: gs://griffith-lab-cromwell/input_data/vep.zip

somaticExome.vep_ensembl_version: '95'

somaticExome.scatter_count: 2

somaticExome.vep_to_table_fields:
- Consequence
- SYMBOL
- Feature_type
- Feature
- HGVSc
- HGVSp
- cDNA_position
- CDS_position
- Protein_position
- Amino_acids
- Codons
- HGNC_ID
- Existing_variation
- gnomADe_AF
- CLIN_SIG
- SOMATIC
- PHENO

somaticExome.bqsr_intervals:
- chr6
- chr17

somaticExome.variants_to_table_fields:
- CHROM
- POS
- REF
- ALT
- set

somaticExome.variants_to_table_genotype_fields:
- GT
- AD
- AF
- DP

somaticExome.per_base_intervals:
- file: gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes_target.interval_list
  label: clinvar

somaticExome.per_target_intervals:
- file: gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes_target.interval_list
  label: acmg_genes

somaticExome.summary_intervals: []

somaticExome.vep_custom_annotations: []

somaticExome.tumor_sample_name: 'H_NJ-HCC1395-HCC1395'

somaticExome.normal_sample_name: 'H_NJ-HCC1395-HCC1395_BL'
