docmCle.reference: gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes.fa
docmCle.reference_fai: gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes.fa.fai
docmCle.reference_dict: gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes.dict

docmCle.tumor_bam: gs://griffith-lab-cromwell/cromwell-executions/alignmentExome/1b955790-a3c1-4cf2-8371-bf415f3525a1/call-alignment/sequenceToBqsr/c6ccbfef-2a84-4f50-be00-396017d1be0c/call-applyBqsr/H_NJ-HCC1395-HCC1395.bam
docmCle.tumor_bam_bai: gs://griffith-lab-cromwell/cromwell-executions/alignmentExome/1b955790-a3c1-4cf2-8371-bf415f3525a1/call-alignment/sequenceToBqsr/c6ccbfef-2a84-4f50-be00-396017d1be0c/call-indexBam/H_NJ-HCC1395-HCC1395.bam.bai

docmCle.normal_bam: gs://griffith-lab-cromwell/cromwell-executions/alignmentExome/0c0a333a-c314-4d01-b6cd-96c8a586a7f5/call-alignment/sequenceToBqsr/43a942b1-163b-4dbe-91e8-0e047c6c6db2/call-applyBqsr/H_NJ-HCC1395-HCC1395_BL.bam
docmCle.normal_bam_bai: gs://griffith-lab-cromwell/cromwell-executions/alignmentExome/0c0a333a-c314-4d01-b6cd-96c8a586a7f5/call-alignment/sequenceToBqsr/43a942b1-163b-4dbe-91e8-0e047c6c6db2/call-indexBam/H_NJ-HCC1395-HCC1395_BL.bam.bai

docmCle.interval_list: gs://griffith-lab-cromwell/cromwell-executions/wf/e985ed7a-80fd-45aa-ae9a-2e20468de5f3/call-intervalListExpand/hla_and_brca_genes_target.expanded.interval_list

docmCle.docm_vcf: gs://griffith-lab-cromwell/input_data/maruska/2021-04-26/somatic_inputs/hla_and_brca_genes_docm.vcf.gz
docmCle.docm_vcf_tbi: gs://griffith-lab-cromwell/input_data/maruska/2021-04-26/somatic_inputs/hla_and_brca_genes_docm.vcf.gz.tbi

docmCle.filter_docm_variants: true
