# BAM BAI
qcExome.bam: gs://griffith-lab-cromwell/cromwell-executions/wf/5e2c28ab-f7dc-49a8-915d-f23ed4159e3d/call-applyBqsr/final.bam
qcExome.bam_bai: gs://griffith-lab-cromwell/cromwell-executions/wf/7491b214-0afd-4c2e-856b-bb7829f30c60/call-indexBam/final.bam.bai

qcExome.reference: gs://griffith-lab-cromwell/input_data/maruska/2021-05-10/somatic_inputs/hla_and_brca_genes.fa
qcExome.reference_fai: gs://griffith-lab-cromwell/input_data/maruska/2021-05-10/somatic_inputs/hla_and_brca_genes.fa.fai
qcExome.reference_dict: gs://griffith-lab-cromwell/input_data/maruska/2021-05-10/somatic_inputs/hla_and_brca_genes.dict

qcExome.bait_intervals: gs://griffith-lab-cromwell/input_data/maruska/2021-05-10/somatic_inputs/hla_and_brca_genes_bait.interval_list
qcExome.target_intervals: gs://griffith-lab-cromwell/input_data/maruska/2021-05-10/somatic_inputs/hla_and_brca_genes_target.interval_list

qcExome.per_base_intervals:
  - file: gs://griffith-lab-cromwell/input_data/maruska/2021-05-10/somatic_inputs/hla_and_brca_genes_target.interval_list
    label: clinvar

qcExome.per_target_intervals:
  - file: gs://griffith-lab-cromwell/input_data/maruska/2021-05-10/somatic_inputs/hla_and_brca_genes_target.interval_list
    label: acmg_genes

qcExome.summary_intervals: []

qcExome.omni_vcf: gs://griffith-lab-cromwell/input_data/maruska/2021-05-10/somatic_inputs/hla_and_brca_genes_omni.vcf.gz
qcExome.omni_vcf_tbi: gs://griffith-lab-cromwell/input_data/maruska/2021-05-10/somatic_inputs/hla_and_brca_genes_omni.vcf.gz.tbi

qcExome.picard_metric_accumulation_level: LIBRARY
