sequenceToBqsr.unaligned:
  - sequence:
      bam: gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/unaligned_subset_bams/normal/2895499331.bam
    readgroup: "@RG\tID:2895499331\tPU:H7HY2CCXX.3\tSM:H_NJ-HCC1395-HCC1395_BL\tLB:H_NJ-HCC1395-HCC1395_BL-lg21-lib1\tPL:Illumina\tCN:WUGSC"
  - sequence:
      bam: gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/unaligned_subset_bams/normal/2895499399.bam
    readgroup: "@RG\tID:2895499399\tPU:H7HY2CCXX.4\tSM:H_NJ-HCC1395-HCC1395_BL\tLB:H_NJ-HCC1395-HCC1395_BL-lg21-lib1\tPL:Illumina\tCN:WUGSC"


sequenceToBqsr.reference: gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes.fa
sequenceToBqsr.reference_fai: gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes.fa.fai
sequenceToBqsr.reference_dict: gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes.dict
sequenceToBqsr.reference_alt: gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes.fa.alt
sequenceToBqsr.reference_amb: gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes.fa.amb
sequenceToBqsr.reference_ann: gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes.fa.ann
sequenceToBqsr.reference_bwt: gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes.fa.bwt
sequenceToBqsr.reference_pac: gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes.fa.pac
sequenceToBqsr.reference_sa: gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes.fa.sa


sequenceToBqsr.bqsr_known_sites:
  - gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes_omni.vcf.gz
  - gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes_dbsnp.vcf.gz
  - gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes_mills.vcf.gz
  - gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes_known_indels.vcf.gz

sequenceToBqsr.bqsr_known_sites_tbi:
  - gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes_omni.vcf.gz.tbi
  - gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes_dbsnp.vcf.gz.tbi
  - gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes_mills.vcf.gz.tbi
  - gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes_known_indels.vcf.gz.tbi


sequenceToBqsr.bqsr_intervals:
  - chr6
  - chr17
