varscanPreAndPostProcessing.reference: gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes.fa
varscanPreAndPostProcessing.reference_fai: gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes.fa.fai
varscanPreAndPostProcessing.reference_dict: gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes.dict

varscanPreAndPostProcessing.tumor_sample_name: H_NJ-HCC1395-HCC1395
varscanPreAndPostProcessing.tumor_bam: gs://griffith-lab-cromwell/cromwell-executions/alignmentExome/1b955790-a3c1-4cf2-8371-bf415f3525a1/call-alignment/sequenceToBqsr/c6ccbfef-2a84-4f50-be00-396017d1be0c/call-applyBqsr/H_NJ-HCC1395-HCC1395.bam
varscanPreAndPostProcessing.tumor_bam_bai: gs://griffith-lab-cromwell/cromwell-executions/alignmentExome/1b955790-a3c1-4cf2-8371-bf415f3525a1/call-alignment/sequenceToBqsr/c6ccbfef-2a84-4f50-be00-396017d1be0c/call-indexBam/H_NJ-HCC1395-HCC1395.bam.bai

varscanPreAndPostProcessing.normal_sample_name: H_NJ-HCC1395-HCC1395_BL
varscanPreAndPostProcessing.normal_bam: gs://griffith-lab-cromwell/cromwell-executions/alignmentExome/0c0a333a-c314-4d01-b6cd-96c8a586a7f5/call-alignment/sequenceToBqsr/43a942b1-163b-4dbe-91e8-0e047c6c6db2/call-applyBqsr/H_NJ-HCC1395-HCC1395_BL.bam
varscanPreAndPostProcessing.normal_bam_bai: gs://griffith-lab-cromwell/cromwell-executions/alignmentExome/0c0a333a-c314-4d01-b6cd-96c8a586a7f5/call-alignment/sequenceToBqsr/43a942b1-163b-4dbe-91e8-0e047c6c6db2/call-indexBam/H_NJ-HCC1395-HCC1395_BL.bam.bai

varscanPreAndPostProcessing.interval_list: gs://griffith-lab-cromwell/cromwell-executions/wf/e985ed7a-80fd-45aa-ae9a-2e20468de5f3/call-intervalListExpand/hla_and_brca_genes_target.expanded.interval_list
varscanPreAndPostProcessing.scatter_count: 50

varscanPreAndPostProcessing.min_coverage: 8
varscanPreAndPostProcessing.min_var_freq: 0.05
varscanPreAndPostProcessing.p_value: 0.99
