varscan.reference: gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes.fa
varscan.reference_fai: gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes.fa.fai
varscan.reference_dict: gs://griffith-lab-cromwell/input_data/maruska/2021-06-17/somatic_inputs/hla_and_brca_genes.dict

# --- Normal ---

varscan.normal_sample_name: H_NJ-HCC1395-HCC1395_BL

varscan.normal_bam: gs://griffith-lab-cromwell/cromwell-executions/alignmentExome/0c0a333a-c314-4d01-b6cd-96c8a586a7f5/call-alignment/sequenceToBqsr/43a942b1-163b-4dbe-91e8-0e047c6c6db2/call-applyBqsr/H_NJ-HCC1395-HCC1395_BL.bam
varscan.normal_bam_bai: gs://griffith-lab-cromwell/cromwell-executions/alignmentExome/0c0a333a-c314-4d01-b6cd-96c8a586a7f5/call-alignment/sequenceToBqsr/43a942b1-163b-4dbe-91e8-0e047c6c6db2/call-indexBam/H_NJ-HCC1395-HCC1395_BL.bam.bai

# --- Tumor ---

varscan.tumor_sample_name: H_NJ-HCC1395-HCC1395

varscan.tumor_bam: gs://griffith-lab-cromwell/cromwell-executions/alignmentExome/1b955790-a3c1-4cf2-8371-bf415f3525a1/call-alignment/sequenceToBqsr/c6ccbfef-2a84-4f50-be00-396017d1be0c/call-applyBqsr/H_NJ-HCC1395-HCC1395.bam
varscan.tumor_bam_bai: gs://griffith-lab-cromwell/cromwell-executions/alignmentExome/1b955790-a3c1-4cf2-8371-bf415f3525a1/call-alignment/sequenceToBqsr/c6ccbfef-2a84-4f50-be00-396017d1be0c/call-indexBam/H_NJ-HCC1395-HCC1395.bam.bai

varscan.min_coverage: 8
varscan.min_var_freq: 0.05
varscan.p_value: 0.99

varscan.roi_bed: gs://griffith-lab-cromwell/cromwell-executions/wf/917060f0-6f51-4c88-9264-f268eaf7d227/call-intervalsToBed/interval_list.bed
