vcfReadcount.reference: gs://griffith-lab-cromwell/input_data/maruska/2021-05-10/somatic_inputs/hla_and_brca_genes.fa
vcfReadcount.reference_dict: gs://griffith-lab-cromwell/input_data/maruska/2021-05-10/somatic_inputs/hla_and_brca_genes.dict
vcfReadcount.reference_fai: gs://griffith-lab-cromwell/input_data/maruska/2021-05-10/somatic_inputs/hla_and_brca_genes.fa.fai

vcfReadcount.vcf: gs://griffith-lab-cromwell/cromwell-executions/wf/734853bb-327b-41a4-828e-c355ee806bc2/call-vep/test.vcf.gz_annotated.vcf


vcfReadcount.tumor_sample_name: H_NJ-HCC1395-HCC1395
vcfReadcount.tumor_bam: gs://griffith-lab-cromwell/cromwell-executions/alignmentExome/1b955790-a3c1-4cf2-8371-bf415f3525a1/call-alignment/sequenceToBqsr/c6ccbfef-2a84-4f50-be00-396017d1be0c/call-applyBqsr/H_NJ-HCC1395-HCC1395.bam
vcfReadcount.tumor_bam_bai: gs://griffith-lab-cromwell/cromwell-executions/alignmentExome/1b955790-a3c1-4cf2-8371-bf415f3525a1/call-alignment/sequenceToBqsr/c6ccbfef-2a84-4f50-be00-396017d1be0c/call-indexBam/H_NJ-HCC1395-HCC1395.bam.bai

vcfReadcount.normal_bam: gs://griffith-lab-cromwell/cromwell-executions/alignmentExome/0c0a333a-c314-4d01-b6cd-96c8a586a7f5/call-alignment/sequenceToBqsr/43a942b1-163b-4dbe-91e8-0e047c6c6db2/call-applyBqsr/H_NJ-HCC1395-HCC1395_BL.bam
vcfReadcount.normal_bam_bai: gs://griffith-lab-cromwell/cromwell-executions/alignmentExome/0c0a333a-c314-4d01-b6cd-96c8a586a7f5/call-alignment/sequenceToBqsr/43a942b1-163b-4dbe-91e8-0e047c6c6db2/call-indexBam/H_NJ-HCC1395-HCC1395_BL.bam.bai

vcfReadcount.normal_sample_name: H_NJ-HCC1395-HCC1395_BL
