Region: REGSUB_REGION  #us-west-2
Image:
  Os: ubuntu2204
HeadNode:
  InstanceType: r5n.4xlarge
  Networking:
    ElasticIp: true
    SubnetId: REGSUB_PUB_SUBNET  # subnet-018d25d2f208a83a2
  DisableSimultaneousMultithreading: false
  Ssh:
    KeyName: REGSUB_KEYNAME  # must be ed25519 for ubuntu
  Dcv:
    Enabled: true
    Port: 8443
  LocalStorage:
    RootVolume:
      Size: 775
      VolumeType: gp3
      DeleteOnTermination: false
    EphemeralVolume:
      MountDir: /head_root
  CustomActions:
    OnNodeConfigured:
      Script: REGSUB_S3_BUCKET_INIT/cluster_boot_config/post_install.sh
      Args:
        - REGSUB_S3_BUCKET_NAME
  Iam:
    S3Access:
      - BucketName: REGSUB_S3_BUCKET_NAME  # daylily-ref
        EnableWriteAccess: False
    AdditionalIamPolicies:
      - Policy: REGSUB_S3_IAM_POLICY  # arn:aws:iam::670484050738:policy/pclusterTagsAndBudget
Scheduling:
  Scheduler: slurm
  SlurmSettings:
    ScaledownIdletime: 10
    Dns:
      DisableManagedDns: false
    QueueUpdateStrategy: DRAIN
  SlurmQueues:
    - Name: i96-5
      CapacityType: SPOT  # SPOT OR DEDICATED
      AllocationStrategy: lowest-price  # lowest-price OR capactity-optimized
      ComputeResources:
        - Name: v24xl
          Instances:
            - InstanceType: r5n.metal  # 96/78
            - InstanceType: r5n.24xlarge  # 96/768  7,2
            - InstanceType: r5dn.metal  # 96/768  7,2
            - InstanceType: r5dn.24xlarge  # 96/768  7,2
            - InstanceType: r5b.metal  # 96/768  7,2
            - InstanceType: r5b.24xlarge  # 96/768  7,2
          MinCount: 0
          MaxCount: 17
          Networking:
            PlacementGroup:
              Enabled: false
          Efa:
            Enabled: false
      Networking:
        SubnetIds:
          - REGSUB_PRIVATE_SUBNET
      CustomActions:
        OnNodeConfigured:
          Script: REGSUB_S3_BUCKET_INIT/cluster_boot_config/post_install.sh
      Iam:
        S3Access:
          - BucketName: REGSUB_S3_BUCKET_NAME
            EnableWriteAccess: False
        AdditionalIamPolicies:
          - Policy: REGSUB_S3_IAM_POLICY
    - Name: i4-5
      CapacityType: SPOT
      AllocationStrategy: lowest-price
      ComputeResources:
        - Name: v2xl
          Instances:
            - InstanceType: r5.2xlarge  # 8/64
            - InstanceType: r5b.2xlarge  # 8/64
            - InstanceType: r5dn.2xlarge  # 8/64
            - InstanceType: r5n.2xlarge  #  8/64
            - InstanceType: r5d.2xlarge  #  8/64
          MinCount: 0
          MaxCount: 16
          Networking:
            PlacementGroup:
              Enabled: false
          Efa:
            Enabled: false
      Networking:
        SubnetIds:
          - REGSUB_PRIVATE_SUBNET
      CustomActions:
        OnNodeConfigured:
          Script: REGSUB_S3_BUCKET_INIT/cluster_boot_config/post_install.sh
      Iam:
        S3Access:
          - BucketName: REGSUB_S3_BUCKET_NAME
            EnableWriteAccess: False
        AdditionalIamPolicies:
          - Policy: REGSUB_S3_IAM_POLICY
Monitoring:
  Logs:
    CloudWatch:
      Enabled: true
      RetentionInDays: 3  # must be 0,1,3,5,7,14,30,60,90...
SharedStorage:  # This is the local FS which is expensive but fast, could be swapped for EFS, etc.
  - MountDir: /fsx
    Name: fsx-for-daylily-data  # WARNING, EDIT NAME WILL DEL EXISTING DATA
    StorageType: FsxLustre
    FsxLustreSettings:
      ImportPath: REGSUB_S3_BUCKET_REF/data/
      StorageCapacity: 4800
      DeploymentType: SCRATCH_2
      AutoImportPolicy: NEW_CHANGED_DELETED
Tags:  # TAGs necessary for per-user/project/job cost tracking
  - Key: aws-parallelcluster-username
    Value: NA
  - Key: aws-parallelcluster-jobid
    Value: NA
  - Key: aws-parallelcluster-project
    Value: NA 
