Region: REGSUB_REGION  #us-west-2
Image:
  Os: centos7
HeadNode:
  InstanceType: r5n.4xlarge
  Networking:
    ElasticIp: true
    SubnetId: REGSUB_PUB_SUBNET  # subnet-018d25d2f208a83a2
  DisableSimultaneousMultithreading: false
  Ssh:
    KeyName: REGSUB_KEYNAME  # daylily
  Dcv:
    Enabled: true
    Port: 8443
  LocalStorage:
    RootVolume:
      Size: 500
      VolumeType: gp3
      DeleteOnTermination: false
    EphemeralVolume:
      MountDir: /head_root
  CustomActions:
    OnNodeConfigured:
      Script: REGSUB_S3_BUCKET_INIT/cluster_boot_config/post_install.sh
  Iam:
    S3Access:
      - BucketName: REGSUB_S3_BUCKET_NAME  # daylily-ref
        EnableWriteAccess: False
    AdditionalIamPolicies:
      - Policy: REGSUB_S3_IAM_POLICY  # arn:aws:iam::670484050738:policy/pclusterTagsAndBudget
Scheduling:
  Scheduler: slurm
  SlurmSettings:
    ScaledownIdletime: 5
    Dns:
      DisableManagedDns: false
    QueueUpdateStrategy: DRAIN
  SlurmQueues:
    - Name: i96-5
      CapacityType: SPOT  # SPOT OR DEDICATED
      AllocationStrategy: lowest-price  # lowest-price OR capactity-optimized
      ComputeResources:
        - Name: v24xl
          Instances:
            - InstanceType: m5.24xlarge  # 96/384 4.6,1.6
            - InstanceType: m5d.metal  # 96/384  5.4,1.6
            - InstanceType: c5.24xlarge 96/192  4,1.6
            - InstanceType: m5.metal  # 96/384  4,1.8
            - InstanceType: c5d.metal  # 96/192  4.6,2  
          MinCount: 0
          MaxCount: 12
          Networking:
            PlacementGroup:
              Enabled: false
          Efa:
            Enabled: false
      Networking:
        SubnetIds:
          - REGSUB_PRIVATE_SUBNET
      CustomActions:
        OnNodeConfigured:
          Script: REGSUB_S3_BUCKET_INIT/cluster_boot_config/post_install.sh
      Iam:
        S3Access:
          - BucketName: REGSUB_S3_BUCKET_NAME
            EnableWriteAccess: False
        AdditionalIamPolicies:
          - Policy: REGSUB_S3_IAM_POLICY
    - Name: i64-5
      CapacityType: SPOT
      AllocationStrategy: lowest-price
      ComputeResources:
        - Name: v16xl
          Instances:
            - InstanceType: c5.18xlarge  # 72/144 3,1
            - InstanceType: r5.16xlarge  # 64/512  4,1.1
            - InstanceType: c5d.18xlarge  # 72/144 3,1.1
          MinCount: 0
          MaxCount: 12
          Networking:
            PlacementGroup:
              Enabled: false
          Efa:
            Enabled: false
      Networking:
        SubnetIds:
          - REGSUB_PRIVATE_SUBNET
      CustomActions:
        OnNodeConfigured:
          Script: REGSUB_S3_BUCKET_INIT/cluster_boot_config/post_install.sh
      Iam:
        S3Access:
          - BucketName: REGSUB_S3_BUCKET_NAME
            EnableWriteAccess: False
        AdditionalIamPolicies:
          - Policy: REGSUB_S3_IAM_POLICY
    - Name: i32-5
      CapacityType: SPOT
      AllocationStrategy: lowest-price
      ComputeResources:
        - Name: v8xl
          Instances:
            - InstanceType: r5b.8xlarge  # 32/256  2,0.7
            - InstanceType: m5.8xlarge  # 32/128  1.5,0.7
            - InstanceType: r5.8xlarge  # 32/256  2,0.5
            - InstanceType: r5d.8xlarge  # 32/256   2.3,0.8
          MinCount: 0
          MaxCount: 12
          Networking:
            PlacementGroup:
              Enabled: false
          Efa:
            Enabled: false
      Networking:
        SubnetIds:
          - REGSUB_PRIVATE_SUBNET
      CustomActions:
        OnNodeConfigured:
          Script: REGSUB_S3_BUCKET_INIT/cluster_boot_config/post_install.sh
      Iam:
        S3Access:
          - BucketName: REGSUB_S3_BUCKET_NAME
            EnableWriteAccess: False
        AdditionalIamPolicies:
          - Policy: REGSUB_S3_IAM_POLICY
    - Name: i16-5
      CapacityType: SPOT
      AllocationStrategy: lowest-price
      ComputeResources:
        - Name: v4xl
          Instances:
            - InstanceType: r5b.4xlarge  # 16/128  1.2,0.6
            - InstanceType: r5dn.4xlarge  # 16/128  1.3,0.5
            - InstanceType: r5n.4xlarge  # 16/128  1.1,0.6
            - InstanceType: m5.4xlarge  # 16/64  1.4, 0.4
            - InstanceType: m5d.4xlarge # 16/64  0.9,0.5
            - InstanceType: r5d.4xlarge # 16/128 1.2,0.5
          MinCount: 0
          MaxCount: 8
          Networking:
            PlacementGroup:
              Enabled: false
          Efa:
            Enabled: false
      Networking:
        SubnetIds:
          - REGSUB_PRIVATE_SUBNET
      CustomActions:
        OnNodeConfigured:
          Script: REGSUB_S3_BUCKET_INIT/cluster_boot_config/post_install.sh
      Iam:
        S3Access:
          - BucketName: REGSUB_S3_BUCKET_NAME
            EnableWriteAccess: False
        AdditionalIamPolicies:
          - Policy: REGSUB_S3_IAM_POLICY
    - Name: i4-5
      CapacityType: SPOT
      AllocationStrategy: lowest-price
      ComputeResources:
        - Name: v2xl
          Instances:
            - InstanceType: r5.2xlarge  # 8/64  0.5,.1
            - InstanceType: r5b.2xlarge  # 8/64 0.6,0.3
            - InstanceType: r5dn.2xlarge  # 8/64 0.7,0.3
            - InstanceType: r5n.2xlarge  #  8/64 0.6,0.3
            - InstanceType: r5d.2xlarge  #  8/64 0.5,0.3
          MinCount: 0
          MaxCount: 8
          Networking:
            PlacementGroup:
              Enabled: false
          Efa:
            Enabled: false
      Networking:
        SubnetIds:
          - REGSUB_PRIVATE_SUBNET
      CustomActions:
        OnNodeConfigured:
          Script: REGSUB_S3_BUCKET_INIT/cluster_boot_config/post_install.sh
      Iam:
        S3Access:
          - BucketName: REGSUB_S3_BUCKET_NAME
            EnableWriteAccess: False
        AdditionalIamPolicies:
          - Policy: REGSUB_S3_IAM_POLICY
    - Name: i128-6
      CapacityType: SPOT
      AllocationStrategy: lowest-price
      ComputeResources:
        - Name: v32xl
          Instances:
            - InstanceType: r6i.32xlarge  # 128/1024  8.0,4.42
            - InstanceType: r6i.metal  # 128/1024  8.0,2.4
            - InstanceType: r6in.32xlarge  # 128/1024 11.1,5.7
            - InstanceType: r6in.metal  # 128/1024  11,4.6
            - InstanceType: r6idn.metal  # 128/1024 12.5,4.6
            - InstanceType: r6idn.32xlarge  # 128/1024  12.5,4.6
            - InstanceType: r6id.32xlarge  # 128/1024 9.6,3.11
            - InstanceType: r6id.metal  # 128/1024 9.6,4.9
          MinCount: 0
          MaxCount: 8
          Networking:
            PlacementGroup:
              Enabled: false
          Efa:
            Enabled: true
      Networking:
        SubnetIds:
          - REGSUB_PRIVATE_SUBNET
      CustomActions:
        OnNodeConfigured:
          Script: REGSUB_S3_BUCKET_INIT/cluster_boot_config/post_install.sh
      Iam:
        S3Access:
          - BucketName: REGSUB_S3_BUCKET_NAME
            EnableWriteAccess: False
        AdditionalIamPolicies:
          - Policy: REGSUB_S3_IAM_POLICY
    - Name: a192-6
      CapacityType: SPOT
      AllocationStrategy: capacity-optimized
      ComputeResources:
        - Name: v48xl
          Instances:
            - InstanceType: r6a.48xlarge  # 192/1536 4.3 
            - InstanceType: r6a.metal  # 192/1536
            - InstanceType: c6a.metal # 192/384
            - InstanceType: c6a.48xlarge  # 192/384
            - InstanceType: m6a.metal # 192/768
            - InstanceType: m6a.48xlarge # 192/768
          MinCount: 0
          MaxCount: 8
          Networking:
            PlacementGroup:
              Enabled: false
          Efa:
            Enabled: true
      Networking:
        SubnetIds:
          - REGSUB_PRIVATE_SUBNET
Monitoring:
  Logs:
    CloudWatch:
      Enabled: true
      RetentionInDays: 14
SharedStorage:  # This is the local FS which is expensive but fast, could be swapped for EFS, etc.
  - MountDir: /fsx
    Name: fsx-for-daylily-data  # WARNING, EDIT NAME WILL DEL EXISTING DATA
    StorageType: FsxLustre
    FsxLustreSettings:
      ImportPath: REGSUB_S3_BUCKET_REF/data/
      StorageCapacity: 4800
      DeploymentType: SCRATCH_2
      AutoImportPolicy: NEW_CHANGED_DELETED
Tags:  # TAGs necessary for per-user/project/job cost tracking
  - Key: aws-parallelcluster-username
    Value: NA
  - Key: aws-parallelcluster-jobid
    Value: NA
  - Key: aws-parallelcluster-project
    Value: NA