Region: us-west-2
Image:
  Os: centos7
HeadNode:
  InstanceType: r5n.4xlarge
  Networking:
    ElasticIp: true
    SubnetId: subnet-018d25d2f208a83a2
  DisableSimultaneousMultithreading: false
  Ssh:
    KeyName: daylily
  Dcv:
    Enabled: true
    Port: 8443
  LocalStorage:
    RootVolume:
      Size: 500
      VolumeType: gp3
      DeleteOnTermination: false
    EphemeralVolume:
      MountDir: /head_root
  CustomActions:
    OnNodeConfigured:
      Script: s3://daylily-ref/cluster_boot_config/post_install.sh
  Iam:
    S3Access:
      - BucketName: daylily-ref
        EnableWriteAccess: False
    AdditionalIamPolicies:
      - Policy: arn:aws:iam::670484050738:policy/pclusterTagsAndBudget
Scheduling:
  Scheduler: slurm
  SlurmSettings:
    ScaledownIdletime: 5
    Dns:
      DisableManagedDns: false
    QueueUpdateStrategy: DRAIN
  SlurmQueues:
    - Name: i96-5
      CapacityType: SPOT
      AllocationStrategy: capacity-optimized
      ComputeResources:
        - Name: v24xl
          Instances:
            - InstanceType: r5n.metal  # 96/78
            - InstanceType: r5n.24xlarge  # 96/768  7,2
            - InstanceType: r5dn.metal  # 96/768  7,2
            - InstanceType: r5dn.24xlarge  # 96/768  7,2
            - InstanceType: r5b.metal  # 96/768  7,2
            - InstanceType: r5b.24xlarge  # 96/768  7,2
          MinCount: 0
          MaxCount: 10
          Networking:
            PlacementGroup:
              Enabled: false
          Efa:
            Enabled: false
      Networking:
        SubnetIds:
          - subnet-0aafeaa872d546fc4
      CustomActions:
        OnNodeConfigured:
          Script: s3://daylily-ref/cluster_boot_config/post_install.sh
      Iam:
        S3Access:
          - BucketName: daylily-ref
            EnableWriteAccess: False
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::670484050738:policy/pclusterTagsAndBudget
    - Name: i64-5
      CapacityType: SPOT
      AllocationStrategy: capacity-optimized
      ComputeResources:
        - Name: v16xl
          Instances:
            - InstanceType: r5b.16xlarge  # 64/512  4,1
            - InstanceType: r5dn.16xlarge  # 64/512  4,1
            - InstanceType: r5n.16xlarge  # 64/512   5,3
          MinCount: 0
          MaxCount: 8
          Networking:
            PlacementGroup:
              Enabled: false
          Efa:
            Enabled: false
      Networking:
        SubnetIds:
          - subnet-0aafeaa872d546fc4
      CustomActions:
        OnNodeConfigured:
          Script: s3://daylily-ref/cluster_boot_config/post_install.sh
      Iam:
        S3Access:
          - BucketName: daylily-ref
            EnableWriteAccess: False
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::670484050738:policy/pclusterTagsAndBudget
    - Name: i32-5
      CapacityType: SPOT
      AllocationStrategy: capacity-optimized
      ComputeResources:
        - Name: v8xl
          Instances:
            - InstanceType: r5b.8xlarge  # 32/256  2,1
            - InstanceType: r5dn.8xlarge  # 32/256  3,1
            - InstanceType: r5n.8xlarge  # 32/256   2,1
          MinCount: 0
          MaxCount: 6
          Networking:
            PlacementGroup:
              Enabled: false
          Efa:
            Enabled: false
      Networking:
        SubnetIds:
          - subnet-0aafeaa872d546fc4
      CustomActions:
        OnNodeConfigured:
          Script: s3://daylily-ref/cluster_boot_config/post_install.sh
      Iam:
        S3Access:
          - BucketName: daylily-ref
            EnableWriteAccess: False
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::670484050738:policy/pclusterTagsAndBudget
    - Name: i16-5
      CapacityType: SPOT
      AllocationStrategy: capacity-optimized
      ComputeResources:
        - Name: v4xl
          Instances:
            - InstanceType: r5b.4xlarge  # 16/128
            - InstanceType: r5dn.4xlarge  # 16/128
            - InstanceType: r5n.4xlarge  # 16/128
          MinCount: 0
          MaxCount: 8
          Networking:
            PlacementGroup:
              Enabled: false
          Efa:
            Enabled: false
      Networking:
        SubnetIds:
          - subnet-0aafeaa872d546fc4
      CustomActions:
        OnNodeConfigured:
          Script: s3://daylily-ref/cluster_boot_config/post_install.sh
      Iam:
        S3Access:
          - BucketName: daylily-ref
            EnableWriteAccess: False
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::670484050738:policy/pclusterTagsAndBudget
    - Name: i4-5
      CapacityType: SPOT
      AllocationStrategy: capacity-optimized
      ComputeResources:
        - Name: v2xl
          Instances:
            - InstanceType: r5.2xlarge  # 8/64
            - InstanceType: r5b.2xlarge  # 8/64
            - InstanceType: r5dn.2xlarge  # 8/64
            - InstanceType: r5n.2xlarge  #  8/64
            - InstanceType: r5d.2xlarge  #  8/64
          MinCount: 0
          MaxCount: 8
          Networking:
            PlacementGroup:
              Enabled: false
          Efa:
            Enabled: false
      Networking:
        SubnetIds:
          - subnet-0aafeaa872d546fc4
      CustomActions:
        OnNodeConfigured:
          Script: s3://daylily-ref/cluster_boot_config/post_install.sh
      Iam:
        S3Access:
          - BucketName: daylily-ref
            EnableWriteAccess: False
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::670484050738:policy/pclusterTagsAndBudget
    - Name: i128-6
      CapacityType: SPOT
      AllocationStrategy: capacity-optimized
      ComputeResources:
        - Name: v32xl
          Instances:
            - InstanceType: r6i.32xlarge  # 128/1024  8.0,6.2
            - InstanceType: r6i.metal  # 128/1024  8.0,2.4
            - InstanceType: r6in.32xlarge  # 128/1024 11.1,5.7
            - InstanceType: r6idn.32xlarge  # 128/1024  12.5,5.2
            - InstanceType: r6id.32xlarge  # 128/1024 9.6,3.11
            - InstanceType: r6id.metal  # 128/1024 9.6,3.11
          MinCount: 0
          MaxCount: 8
          Networking:
            PlacementGroup:
              Enabled: false
          Efa:
            Enabled: true
      Networking:
        SubnetIds:
          - subnet-0aafeaa872d546fc4
      CustomActions:
        OnNodeConfigured:
          Script: s3://daylily-ref/cluster_boot_config/post_install.sh
      Iam:
        S3Access:
          - BucketName: daylily-ref
            EnableWriteAccess: False
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::670484050738:policy/pclusterTagsAndBudget
    - Name: a192-6
      CapacityType: SPOT
      AllocationStrategy: capacity-optimized
      ComputeResources:
        - Name: v48xl
          Instances:
            - InstanceType: r6a.48xlarge  # 192/1536 4.3 
            - InstanceType: r6a.metal  # 192/1536
            - InstanceType: c6a.metal # 192/384 
          MinCount: 0
          MaxCount: 8
          Networking:
            PlacementGroup:
              Enabled: false
          Efa:
            Enabled: true
      Networking:
        SubnetIds:
          - subnet-0aafeaa872d546fc4
      CustomActions:
        OnNodeConfigured:
          Script: s3://daylily-ref/cluster_boot_config/post_install.sh
      Iam:
        S3Access:
          - BucketName: daylily-ref
            EnableWriteAccess: False
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::670484050738:policy/pclusterTagsAndBudget
Monitoring:
  Logs:
    CloudWatch:
      Enabled: true
      RetentionInDays: 14
SharedStorage:
  - MountDir: /fsx
    Name: fsx-for-day-data  # WARNING, EDIT NAME WILL DEL EXISTING DATA
    StorageType: FsxLustre
    FsxLustreSettings:
      ImportPath: s3://daylily-reference-data/data/
      StorageCapacity: 4800
      DeploymentType: SCRATCH_2
      AutoImportPolicy: NEW_CHANGED_DELETED
Tags:
  - Key: aws-parallelcluster-username
    Value: NA
  - Key: aws-parallelcluster-jobid
    Value: NA
  - Key: aws-parallelcluster-project
    Value: NA